
import type { Product } from './types';

export const products: Product[] = [
  // --- FURNITURE: Turkey Collections ---
  {
    id: 'prod-60',
    name: 'Tufted Turkey Chairs',
    description: 'Ultra-luxurious Tufted Turkey chairs, the pinnacle of comfort and royal elegance for your master bedroom or living suite.',
    price: 8000000,
    imageId: 'prod-60',
    category: 'Turkey Collections',
  },
  
  // --- FURNITURE: Bedroom ---
  {
    id: 'prod-49',
    name: 'Comfortable and Stylish Bed',
    description: 'Premium upholstered bed frame designed for maximum comfort and a sophisticated modern aesthetic.',
    price: 850000,
    imageId: 'prod-49',
    category: 'Bedroom',
  },
  {
    id: 'prod-66',
    name: 'classic damask accent',
    description: 'Classic damask accent piece to enhance your interior aesthetic.',
    price: 600000,
    imageId: 'prod-66',
    category: 'Bedroom',
  },
  {
    id: 'prod-74',
    name: 'green curvette',
    description: 'Distinctive green curvette furniture piece for a pop of color and style.',
    price: 600000,
    imageId: 'prod-74',
    category: 'Bedroom',
  },
  {
    id: 'prod-77',
    name: 'machiatto set',
    description: 'Elegant machiatto furniture set, blending comfort with style.',
    price: 600000,
    imageId: 'prod-77',
    category: 'Bedroom',
  },
  {
    id: 'prod-85',
    name: 'rocky set',
    description: 'Durable and stylish rocky furniture set for modern living.',
    price: 600000,
    imageId: 'prod-85',
    category: 'Bedroom',
  },
  {
    id: 'prod-97',
    name: 'varta console',
    description: 'Premium varta console table, a masterpiece of design.',
    price: 800000,
    imageId: 'prod-97',
    category: 'Bedroom',
  },
  {
    id: 'prod-100',
    name: 'wardrobe with inbuilt light',
    description: 'Functional wardrobe with inbuilt light for ultimate convenience.',
    price: 950000,
    imageId: 'prod-100',
    category: 'Bedroom',
  },

  // --- FURNITURE: Living Room ---
  {
    id: 'prod-37',
    name: 'ARMANI CASSA SET',
    description: 'Exquisite Armani Cassa sofa set designed for the ultimate luxury living experience.',
    price: 2500000,
    imageId: 'prod-37',
    category: 'Living Room',
  },
  {
    id: 'prod-42',
    name: 'osmo sofa',
    description: 'Modern Osmo sofa featuring clean lines and premium comfort for contemporary spaces.',
    price: 2500000,
    imageId: 'prod-42',
    category: 'Living Room',
  },
  {
    id: 'prod-45',
    name: 'VITALE SOFA SET',
    description: 'Premium Vitale sofa set, a masterpiece of craftsmanship and timeless elegance.',
    price: 3500000,
    imageId: 'prod-45',
    category: 'Living Room',
  },
  {
    id: 'prod-65',
    name: 'chocolate center table',
    description: 'Stylish chocolate center table, a perfect centerpiece for your living room.',
    price: 500000,
    imageId: 'prod-65',
    category: 'Living Room',
  },
  {
    id: 'prod-70',
    name: 'fehdi console',
    description: 'Minimalist and stylish fehdi console for contemporary homes.',
    price: 650000,
    imageId: 'prod-70',
    category: 'Living Room',
  },
  {
    id: 'prod-72',
    name: 'fire flame tv stand',
    description: 'Unique fire flame design TV stand that makes a bold statement.',
    price: 300000,
    imageId: 'prod-72',
    category: 'Living Room',
  },
  {
    id: 'prod-73',
    name: 'garrah console',
    description: 'Exquisitely crafted garrah console table for high-end interiors.',
    price: 800000,
    imageId: 'prod-73',
    category: 'Living Room',
  },

  // --- FURNITURE: Dinning Set ---
  {
    id: 'prod-61',
    name: '6 seater grey italian bursa',
    description: 'Luxury 6 seater grey Italian Bursa set for a sophisticated dining area.',
    price: 1500000,
    imageId: 'prod-61',
    category: 'Dinning Set',
  },

  // --- FURNITURE: House Decoratives ---
  {
    id: 'prod-63',
    name: 'antelope deer decor',
    description: 'Artistic antelope deer decorative piece to add charm to your space.',
    price: 150000,
    imageId: 'prod-63',
    category: 'House Decoratives',
  },
  {
    id: 'prod-47',
    name: 'beautiful wreath flower',
    description: 'Artistic wreath flower decorative piece to enhance your home\'s interior charm.',
    price: 30000,
    imageId: 'prod-47',
    category: 'House Decoratives',
  },
  {
    id: 'prod-64',
    name: 'candle dinning lamp set',
    description: 'Elegant candle dining lamp set for a warm and inviting atmosphere.',
    price: 300000,
    imageId: 'prod-64',
    category: 'House Decoratives',
  },
  {
    id: 'prod-67',
    name: 'clock gobe',
    description: 'Unique clock gobe decor that combines functionality with artistic design.',
    price: 120000,
    imageId: 'prod-67',
    category: 'House Decoratives',
  },
  {
    id: 'prod-78',
    name: 'medium size deer decor',
    description: 'Graceful medium size deer decor to accent your room.',
    price: 120000,
    imageId: 'prod-78',
    category: 'House Decoratives',
  },
  {
    id: 'prod-86',
    name: 'round side table',
    description: 'Versatile round side table, a perfect companion for any room.',
    price: 100000,
    imageId: 'prod-86',
    category: 'House Decoratives',
  },
  {
    id: 'prod-87',
    name: 'small deer decor',
    description: 'Cute small deer decor to bring a touch of nature indoors.',
    price: 100000,
    imageId: 'prod-87',
    category: 'House Decoratives',
  },
  {
    id: 'prod-88',
    name: 'small tree decor',
    description: 'Artistic small tree decor for a sophisticated interior accent.',
    price: 100000,
    imageId: 'prod-88',
    category: 'House Decoratives',
  },
  {
    id: 'prod-89',
    name: 'snow flower set',
    description: 'Beautiful snow flower decorative set for a delicate touch.',
    price: 170000,
    imageId: 'prod-89',
    category: 'House Decoratives',
  },
  {
    id: 'prod-90',
    name: 'standing horse gold decor',
    description: 'Majestic standing horse gold decor, a symbol of elegance.',
    price: 150000,
    imageId: 'prod-90',
    category: 'House Decoratives',
  },
  {
    id: 'prod-91',
    name: 'stoned frame',
    description: 'Unique stoned frame decorative piece for your walls.',
    price: 200000,
    imageId: 'prod-91',
    category: 'House Decoratives',
  },
  {
    id: 'prod-94',
    name: 'triangle clock decor',
    description: 'Modern triangle clock decor, blending timekeeping with art.',
    price: 120000,
    imageId: 'prod-94',
    category: 'House Decoratives',
  },
  {
    id: 'prod-98',
    name: 'wall decor',
    description: 'Elegant wall decor piece to complete your room aesthetic.',
    price: 150000,
    imageId: 'prod-98',
    category: 'House Decoratives',
  },
  {
    id: 'prod-99',
    name: 'wall design mirror',
    description: 'Stylish wall design mirror to brighten and expand your space.',
    price: 340000,
    imageId: 'prod-99',
    category: 'House Decoratives',
  },
  {
    id: 'prod-101',
    name: 'white fur light',
    description: 'Unique and cozy white fur light fixture for a soft ambiance.',
    price: 150000,
    imageId: 'prod-101',
    category: 'House Decoratives',
  },

  // --- FURNITURE: Office ---
  {
    id: 'prod-75',
    name: 'grey sofa',
    description: 'Comfortable and modern grey sofa set for your office or relaxation area.',
    price: 750000,
    imageId: 'prod-75',
    category: 'Office',
  },

  // --- FURNITURE: Side Lamps & Standing Lamps ---
  {
    id: 'prod-48',
    name: 'bed side lamp',
    description: 'Elegant and warm bedside lamp, providing the perfect ambiance for late-night reading.',
    price: 50000,
    imageId: 'prod-48',
    category: 'Side Lamps & Standing Lamps',
  },
  {
    id: 'prod-32',
    name: 'Unique Standing Led Lamp',
    description: 'Elegant standing LED lamp that makes a statement in any living space.',
    price: 95000,
    imageId: 'prod-32',
    category: 'Side Lamps & Standing Lamps',
  },

  // --- LIGHTING: Chandelier Lighting ---
  {
    id: 'prod-3',
    name: 'crystal chandelier',
    description: 'A stunning crystal centerpiece that brings elegance and sparkle to any room.',
    price: 400000,
    imageId: 'prod-3',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-ch-2',
    name: 'crystal chandellier',
    description: 'Exquisite crystal lighting fixture for a refined interior.',
    price: 410000,
    imageId: 'prod-13',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-50',
    name: 'Crystal_Fan_Chandelier with bluethooth',
    description: 'Innovative crystal chandelier that doubles as a high-performance ceiling fan with bluetooth capability.',
    price: 180000,
    imageId: 'prod-50',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-69',
    name: 'elegant and modern crystal chandeier',
    description: 'Breathtakingly elegant and modern crystal chandelier for a touch of luxury.',
    price: 150000,
    imageId: 'prod-69',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-6',
    name: 'LUXURIOUS ROYAL CRYSTAL CHANDELIER',
    description: 'The pinnacle of luxury lighting. A grand royal crystal chandelier for sophisticated spaces.',
    price: 800000,
    imageId: 'prod-6',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-ch-6',
    name: 'luxury crystal gold duplex chandelier',
    description: 'Grand luxury gold duplex chandelier featuring premium crystal accents.',
    price: 350000,
    imageId: 'prod-21',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-ch-7',
    name: 'luxury led ceiling chandelier',
    description: 'Sleek and sparkling luxury LED ceiling chandelier for modern homes.',
    price: 180000,
    imageId: 'prod-58',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-ch-8',
    name: 'luxury vintage crystal chandelier',
    description: 'Classic luxury vintage crystal chandelier with timeless appeal.',
    price: 220000,
    imageId: 'prod-25',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-13',
    name: 'Modern Crystal Chandelier light',
    description: 'Sleek modern chandelier featuring exquisite crystal elements.',
    price: 120000,
    imageId: 'prod-13',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-79',
    name: 'modern crystal chandelier',
    description: 'Timeless modern crystal chandelier for a sophisticated lighting solution.',
    price: 180000,
    imageId: 'prod-79',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-14',
    name: 'Modern Decorative Crystal Chandelier Light',
    description: 'An elegant centerpiece that combines modern design with classic crystal charm.',
    price: 180000,
    imageId: 'prod-14',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-ch-12',
    name: 'modern design crystal chandelier (available in size 500)',
    description: 'Magnificent modern design crystal chandelier, available in 500mm size.',
    price: 160000,
    imageId: 'prod-58',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-57',
    name: 'modern LED crystal chandelier',
    description: 'Sleek and sparkling modern LED crystal chandelier, perfect for contemporary homes.',
    price: 160000,
    imageId: 'prod-57',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-ch-14',
    name: 'modern led spheric chandelier',
    description: 'Artistic modern LED spheric chandelier for a unique lighting statement.',
    price: 200000,
    imageId: 'prod-22',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-ch-15',
    name: 'modern round crystal chandelier',
    description: 'Beautiful modern round crystal chandelier for balanced illumination.',
    price: 350000,
    imageId: 'prod-21',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-21',
    name: 'New Luxury Crystal Gold Duplex Chandelier',
    description: 'Grand luxury gold duplex chandelier featuring premium crystal accents.',
    price: 350000,
    imageId: 'prod-21',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-25',
    name: 'Pure crystal charming Chandelier Light',
    description: 'Charming chandelier crafted from pure crystals for maximum brilliance.',
    price: 400000,
    imageId: 'prod-25',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-ch-18',
    name: 'stylish crystal chandelier size 500',
    description: 'Sleek and sparkling stylish crystal chandelier in 500mm size.',
    price: 140000,
    imageId: 'prod-68',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-30',
    name: 'Unique Decorative LED Chandelier',
    description: 'Decorative LED chandelier with a unique, eye-catching structure.',
    price: 220000,
    imageId: 'prod-30',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-ch-20',
    name: 'unique high quality crystal chandelier',
    description: 'Breathtaking high quality crystal chandelier that radiates brilliance.',
    price: 180000,
    imageId: 'prod-59',
    category: 'Chandelier Lighting',
  },
  {
    id: 'prod-ch-21',
    name: 'unique modern crystal chandelier (available in size 400 & 500)',
    description: 'One-of-a-kind unique modern crystal chandelier, available in sizes 400 and 500.',
    price: 160000,
    imageId: 'prod-13',
    category: 'Chandelier Lighting',
  },

  // --- LIGHTING: Ceiling & Pop Lighting ---
  {
    id: 'prod-106',
    name: 'bluetooth pop light',
    description: 'Modern bluetooth-enabled POP light with versatile ceiling illumination.',
    price: 55000,
    imageId: 'prod-106',
    category: 'Ceiling & Pop Lighting',
  },
  {
    id: 'prod-52',
    name: 'decorative POP light',
    description: 'Eye-catching decorative POP light fixture to add artistic flair to your ceiling designs.',
    price: 60000,
    imageId: 'prod-52',
    category: 'Ceiling & Pop Lighting',
  },
  {
    id: 'prod-107',
    name: 'design pop light',
    description: 'Stylishly designed POP light for premium architectural aesthetics.',
    price: 70000,
    imageId: 'prod-107',
    category: 'Ceiling & Pop Lighting',
  },
  {
    id: 'prod-108',
    name: 'okeli rope light',
    description: 'High-quality Okeli rope light for soft and even ambient lighting.',
    price: 40000,
    imageId: 'prod-108',
    category: 'Ceiling & Pop Lighting',
  },
  {
    id: 'prod-84',
    name: 'pop decorative light',
    description: 'Artistic POP decorative light fixture for unique ceiling aesthetics.',
    price: 70000,
    imageId: 'prod-84',
    category: 'Ceiling & Pop Lighting',
  },
  {
    id: 'prod-109',
    name: 'spot AKT pop light',
    description: 'Powerful Spot AKT POP light. Available in blue and white colors.',
    price: 35000,
    imageId: 'prod-109',
    category: 'Ceiling & Pop Lighting',
  },
  {
    id: 'prod-93',
    name: 'track light',
    description: 'Available in white and black 20W-40W. Prices: 20W - ₦7,000, 40W - ₦10,000, Rail per meter - ₦2,000.',
    price: 7000,
    imageId: 'prod-93',
    category: 'Ceiling & Pop Lighting',
  },
  {
    id: 'prod-93-alt',
    name: 'track_light',
    description: 'Industrial-style track lighting per unit.',
    price: 7000,
    imageId: 'prod-93',
    category: 'Ceiling & Pop Lighting',
  },

  // --- LIGHTING: Outdoor Lighting ---
  {
    id: 'out-1',
    name: 'outdoor light',
    description: 'Sleek and durable outdoor light fixture, perfect for illuminating pathways or porches.',
    price: 8000,
    imageId: 'prod-11',
    category: 'Outdoor Lighting',
  },
  {
    id: 'out-2',
    name: 'outdoor light',
    description: 'Weather-resistant decorative outdoor light for a stylish exterior ambiance.',
    price: 8000,
    imageId: 'prod-35',
    category: 'Outdoor Lighting',
  },
  {
    id: 'out-3',
    name: 'outdoor light',
    description: 'Premium quality outdoor wall light with efficient illumination.',
    price: 11000,
    imageId: 'prod-71',
    category: 'Outdoor Lighting',
  },
  {
    id: 'out-4',
    name: 'outdoor light',
    description: 'Modern and versatile outdoor light suitable for various architectural styles.',
    price: 12000,
    imageId: 'prod-11',
    category: 'Outdoor Lighting',
  },
  {
    id: 'out-5',
    name: 'outdoor light',
    description: 'High-performance outdoor light for secure and bright surroundings.',
    price: 17000,
    imageId: 'prod-80',
    category: 'Outdoor Lighting',
  },
  {
    id: 'out-6',
    name: 'outdoor light',
    description: 'Elegant outdoor lighting solution with a sophisticated finish.',
    price: 18000,
    imageId: 'prod-11',
    category: 'Outdoor Lighting',
  },
  {
    id: 'out-7',
    name: 'outdoor light',
    description: 'Luxurious grand outdoor light fixture for a stately home exterior.',
    price: 25000,
    imageId: 'prod-7',
    category: 'Outdoor Lighting',
  },
  {
    id: 'out-8',
    name: 'outdoor light',
    description: 'The ultimate in outdoor illumination, combining power with exquisite design.',
    price: 35000,
    imageId: 'prod-8',
    category: 'Outdoor Lighting',
  },
  {
    id: 'prod-71',
    name: 'fence light',
    description: 'Durable fence light for effective and stylish outdoor lighting.',
    price: 7000,
    imageId: 'prod-71',
    category: 'Outdoor Lighting',
  },

  // --- LIGHTING: Pendant & Drop Lighting ---
  {
    id: 'prod-1',
    name: '3 in 1 Dropping Light',
    description: 'Industrial style dropping light featuring rustic rope accents and protective metal cages.',
    price: 45000,
    imageId: 'prod-1',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-2',
    name: '5 in 1 Dropping Light',
    description: 'A grander version of our classic dropping light, featuring five elegant pendant bulbs.',
    price: 75000,
    imageId: 'prod-2',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-5',
    name: 'LED Drop Light',
    description: 'Modern energy-efficient LED drop light. Sleek and minimalist design.',
    price: 40000,
    imageId: 'prod-5',
    isSoldOut: true,
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-10',
    name: 'Luxury Unique Pendant drop Light',
    description: 'One-of-a-kind pendant drop light for those who value unique design.',
    price: 80000,
    imageId: 'prod-10',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-15',
    name: 'Modern Design Singlr Drop Pendant Light',
    description: 'A minimalist single drop pendant light for a clean, modern aesthetic.',
    price: 60000,
    imageId: 'prod-15',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-16',
    name: 'Modern Four Drop Led Pendant Light',
    description: 'Striking four-drop LED pendant light for balanced, elegant illumination.',
    price: 75000,
    imageId: 'prod-16',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-20',
    name: 'New Design Crystal Drop Light',
    description: 'A fresh, new design in crystal drop lighting for modern interiors.',
    price: 75000,
    imageId: 'prod-20',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-22',
    name: 'New Unique Design Led Light',
    description: 'A unique LED lighting solution with a cutting-edge design.',
    price: 120000,
    imageId: 'prod-22',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-27',
    name: 'Unique 3Way Round Led Light',
    description: 'A unique 3-way round LED light for versatile illumination patterns.',
    price: 75000,
    imageId: 'prod-27',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-28',
    name: 'Unique 4 way Ball Led Drop Light',
    description: 'Creative 4-way ball LED drop light for a playful yet elegant look.',
    price: 80000,
    imageId: 'prod-28',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-29',
    name: 'Unique Butterfly Led Dropping Light',
    description: 'Enchanting butterfly-themed LED dropping light for magical spaces.',
    price: 120000,
    imageId: 'prod-29',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-31',
    name: 'Unique Design 2 way Drop Light',
    description: 'Versatile 2-way LED drop light with a unique contemporary design.',
    price: 35000,
    imageId: 'prod-31',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-33',
    name: 'Unique Track LED Drop Light',
    description: 'Industrial-inspired track LED light perfect for modern galleries and hallways.',
    price: 100000,
    imageId: 'prod-33',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-68',
    name: 'compact nordic crystal drop light',
    description: 'Sleek compact Nordic crystal drop light for modern interiors.',
    price: 140000,
    imageId: 'prod-68',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-92',
    name: 'stylish led drop light',
    description: 'Contemporary stylish LED drop light for balanced illumination.',
    price: 45000,
    imageId: 'prod-92',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-95',
    name: 'unique bird light',
    description: 'Artistic unique bird light fixture for a creative interior.',
    price: 85000,
    imageId: 'prod-95',
    category: 'Pendant & Drop Lighting',
  },
  {
    id: 'prod-96',
    name: 'unique drop light',
    description: 'One-of-a-kind unique drop light for personalized spaces.',
    price: 70000,
    imageId: 'prod-96',
    category: 'Pendant & Drop Lighting',
  },

  // --- LIGHTING: Wall Bracket Lighting ---
  {
    id: 'prod-46',
    name: '2 in 1 Led Wall Bracket light',
    description: 'Functional and stylish 2-in-1 LED wall bracket light with modern illumination.',
    price: 22000,
    imageId: 'prod-46',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-56',
    name: 'Modern and energy-efficient LED wall bracket',
    description: 'Eco-friendly and high-performance LED wall bracket for modern lighting needs.',
    price: 22000,
    imageId: 'prod-56',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-51',
    name: 'decorative LED wall bracket',
    description: 'Sophisticated decorative LED wall bracket that serves as a beautiful accent piece.',
    price: 20000,
    imageId: 'prod-51',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-53',
    name: 'decorative wall bracket light',
    description: 'Classic decorative wall bracket light with a touch of modern craftsmanship.',
    price: 24000,
    imageId: 'prod-53',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-54',
    name: 'durable and stylish Led wall bracket',
    description: 'Long-lasting and aesthetically pleasing LED wall bracket for your home.',
    price: 19000,
    imageId: 'prod-54',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-55',
    name: 'Durable LED wall bracket',
    description: 'Reliable LED wall bracket featuring a minimalist yet stylish design.',
    price: 19000,
    imageId: 'prod-55',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-4',
    name: 'Deer Wall Bracket Light',
    description: 'Unique nature-inspired wall bracket light featuring a majestic deer design.',
    price: 22000,
    imageId: 'prod-4',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-7',
    name: 'Luxury Home Rooms wall Bracket Light',
    description: 'Premium wall bracket light designed for high-end residential interiors.',
    price: 25000,
    imageId: 'prod-7',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-8',
    name: 'Luxury Double Golden Bird Wall Bracket Light',
    description: 'Artistic lighting fixture featuring two exquisite golden birds.',
    price: 35000,
    imageId: 'prod-8',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-9',
    name: 'Luxury Quality Mounted Wall Bird Light',
    description: 'High-quality mounted wall light with a beautiful bird accent.',
    price: 20000,
    imageId: 'prod-9',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-12',
    name: 'Modern Quality Luxury Christal LED Wall Bracket',
    description: 'A touch of luxury for your walls with high-quality crystal LED lighting.',
    price: 75000,
    imageId: 'prod-12',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-17',
    name: 'Modern Horn Rooms bracket',
    description: 'Unique horn-style wall bracket for a bold and creative lighting statement.',
    price: 25000,
    imageId: 'prod-17',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-18',
    name: 'Modern Room Wall Bracket Light',
    description: 'Versatile wall bracket light perfect for modern bedrooms and living areas.',
    price: 15000,
    imageId: 'prod-18',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-23',
    name: 'Nodic Modern Creative Feather wall bracket',
    description: 'Nordic-inspired creative wall bracket with a delicate feather design.',
    price: 15000,
    imageId: 'prod-23',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-24',
    name: 'Nodic Modern Creative Feather wall Ligh',
    description: 'Artistic Nordic wall light featuring a stunning creative feather motif.',
    price: 20000,
    imageId: 'prod-24',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-34',
    name: 'Unique Wall LED Light',
    description: 'Sculptural wall LED light that provides both illumination and artistic flair.',
    price: 19000,
    imageId: 'prod-34',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-35',
    name: 'Wall bracket Light ',
    description: 'Simple yet elegant wall bracket light for cozy room ambiances.',
    price: 8000,
    imageId: 'prod-35',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-36',
    name: 'Wall bracket light',
    description: 'Durable and stylish wall bracket lighting solution for your home.',
    price: 19000,
    imageId: 'prod-36',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-80',
    name: 'modern led wall bracket',
    description: 'Sleek modern LED wall bracket for effective accent lighting.',
    price: 17000,
    imageId: 'prod-80',
    category: 'Wall Bracket Lighting',
  },
  {
    id: 'prod-83',
    name: 'modern wall bracket with bulb',
    description: 'Functional modern wall bracket complete with bulb for instant use.',
    price: 17000,
    imageId: 'prod-83',
    category: 'Wall Bracket Lighting',
  },

  // --- LIGHTING: BULBS ---
  {
    id: 'prod-102',
    name: 'AKT 5W bulb',
    description: 'High-quality AKT 5W energy-saving bulb.',
    price: 900,
    imageId: 'prod-102',
    category: 'BULBS',
  },
  {
    id: 'prod-103',
    name: 'AKT 15W bulb',
    description: 'Bright and durable AKT 15W LED bulb.',
    price: 1700,
    imageId: 'prod-103',
    category: 'BULBS',
  },
  {
    id: 'prod-104',
    name: 'AKT 18W pop bulb',
    description: 'Specialized AKT 18W pop bulb for modern ceilings.',
    price: 3800,
    imageId: 'prod-104',
    category: 'BULBS',
  },
  {
    id: 'prod-105',
    name: 'DLI 10W bulb',
    description: 'Reliable DLI 10W bulb for consistent illumination.',
    price: 900,
    imageId: 'prod-105',
    category: 'BULBS',
  },
];
