import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'prod-37',
    name: 'ARMANI CASSA SET',
    description: 'Exquisite Armani Cassa sofa set designed for the ultimate luxury living experience.',
    price: 2500000,
    imageId: 'prod-37',
    category: 'Furniture',
  },
  {
    id: 'prod-42',
    name: 'osmo sofa',
    description: 'Modern Osmo sofa featuring clean lines and premium comfort for contemporary spaces.',
    price: 2500000,
    imageId: 'prod-42',
    category: 'Furniture',
  },
  {
    id: 'prod-45',
    name: 'VITALE SOFA SET',
    description: 'Premium Vitale sofa set, a masterpiece of craftsmanship and timeless elegance.',
    price: 3500000,
    imageId: 'prod-45',
    category: 'Furniture',
  },
  {
    id: 'prod-41',
    name: 'MARBLE CONFFETABLE 4 SEATER SET',
    description: 'Luxurious marble coffee table set with four matching seats for a sophisticated interior.',
    price: 1500000,
    imageId: 'prod-41',
    category: 'Furniture',
  },
  {
    id: 'prod-38',
    name: 'grey 4 seater sofa',
    description: 'Spacious and stylish grey 4-seater sofa, perfect for modern families.',
    price: 750000,
    imageId: 'prod-38',
    category: 'Furniture',
  },
  {
    id: 'prod-40',
    name: 'Marble Coffee Table',
    description: 'Elegant marble coffee table that serves as a stunning centerpiece for any room.',
    price: 550000,
    imageId: 'prod-40',
    category: 'Furniture',
  },
  {
    id: 'prod-44',
    name: 'Vista Table',
    description: 'Beautifully crafted Vista table, blending modern aesthetics with functional design.',
    price: 400000,
    imageId: 'prod-44',
    category: 'Furniture',
  },
  {
    id: 'prod-39',
    name: 'Halifax Accent Chair',
    description: 'Distinguished Halifax accent chair, providing both comfort and a touch of class.',
    price: 300000,
    imageId: 'prod-39',
    category: 'Furniture',
  },
  {
    id: 'prod-43',
    name: 'Side table',
    description: 'Versatile and elegant side table, a perfect companion for your sofa or bed.',
    price: 100000,
    imageId: 'prod-43',
    category: 'Furniture',
  },
  {
    id: 'prod-1',
    name: '3 in 1 Dropping Light',
    description: 'Industrial style dropping light featuring rustic rope accents and protective metal cages.',
    price: 45000,
    imageId: 'prod-1',
    category: 'Pendant Light',
  },
  {
    id: 'prod-2',
    name: '5 in 1 Dropping Light',
    description: 'A grander version of our classic dropping light, featuring five elegant pendant bulbs.',
    price: 75000,
    imageId: 'prod-2',
    category: 'Pendant Light',
  },
  {
    id: 'prod-3',
    name: 'Decorative Crystal Chandelier',
    description: 'A stunning decorative piece that brings elegance and sparkle to any room.',
    price: 400000,
    imageId: 'prod-3',
    category: 'Chandelier',
  },
  {
    id: 'prod-4',
    name: 'Deer Wall Bracket Light',
    description: 'Unique nature-inspired wall bracket light featuring a majestic deer design.',
    price: 22000,
    imageId: 'prod-4',
    category: 'Wall Light',
  },
  {
    id: 'prod-5',
    name: 'LED Drop Light',
    description: 'Modern energy-efficient LED drop light. Sleek and minimalist design.',
    price: 40000,
    imageId: 'prod-5',
    isSoldOut: true,
    category: 'Pendant Light',
  },
  {
    id: 'prod-6',
    name: 'Luxurious Royal Crystal Chandelier',
    description: 'The pinnacle of luxury lighting. A grand royal crystal chandelier for sophisticated spaces.',
    price: 800000,
    imageId: 'prod-6',
    category: 'Chandelier',
  },
  {
    id: 'prod-7',
    name: 'Luxury Home Rooms wall Bracket Light',
    description: 'Premium wall bracket light designed for high-end residential interiors.',
    price: 25000,
    imageId: 'prod-7',
    category: 'Wall Light',
  },
  {
    id: 'prod-8',
    name: 'Luxury Double Golden Bird Wall Bracket Light',
    description: 'Artistic lighting fixture featuring two exquisite golden birds.',
    price: 35000,
    imageId: 'prod-8',
    category: 'Wall Light',
  },
  {
    id: 'prod-9',
    name: 'Luxury Quality Mounted Wall Bird Light',
    description: 'High-quality mounted wall light with a beautiful bird accent.',
    price: 20000,
    imageId: 'prod-9',
    category: 'Wall Light',
  },
  {
    id: 'prod-10',
    name: 'Luxury Unique Pendant drop Light',
    description: 'One-of-a-kind pendant drop light for those who value unique design.',
    price: 80000,
    imageId: 'prod-10',
    category: 'Pendant Light',
  },
  {
    id: 'prod-11',
    name: 'Modern Outdoor & Indoor Light',
    description: 'Stylish and versatile light fixture suitable for both modern interior and exterior settings.',
    price: 12000,
    imageId: 'prod-11',
    category: 'Other Lighting',
  },
  {
    id: 'prod-12',
    name: 'Modern Quality Luxury Christal LED Wall Bracket',
    description: 'A touch of luxury for your walls with high-quality crystal LED lighting.',
    price: 75000,
    imageId: 'prod-12',
    category: 'Wall Light',
  },
  {
    id: 'prod-13',
    name: 'Modern Crystal Chandelier light',
    description: 'Sleek modern chandelier featuring exquisite crystal elements.',
    price: 120000,
    imageId: 'prod-13',
    category: 'Chandelier',
  },
  {
    id: 'prod-14',
    name: 'Modern Decorative Crystal Chandelier Light',
    description: 'An elegant centerpiece that combines modern design with classic crystal charm.',
    price: 180000,
    imageId: 'prod-14',
    category: 'Chandelier',
  },
  {
    id: 'prod-15',
    name: 'Modern Design Singlr Drop Pendant Light',
    description: 'A minimalist single drop pendant light for a clean, modern aesthetic.',
    price: 60000,
    imageId: 'prod-15',
    category: 'Pendant Light',
  },
  {
    id: 'prod-16',
    name: 'Modern Four Drop Led Pendant Light',
    description: 'Striking four-drop LED pendant light for balanced, elegant illumination.',
    price: 75000,
    imageId: 'prod-16',
    category: 'Pendant Light',
  },
  {
    id: 'prod-17',
    name: 'Modern Horn Rooms bracket',
    description: 'Unique horn-style wall bracket for a bold and creative lighting statement.',
    price: 25000,
    imageId: 'prod-17',
    category: 'Wall Light',
  },
  {
    id: 'prod-18',
    name: 'Modern Room Wall Bracket Light',
    description: 'Versatile wall bracket light perfect for modern bedrooms and living areas.',
    price: 15000,
    imageId: 'prod-18',
    category: 'Wall Light',
  },
  {
    id: 'prod-19',
    name: 'New Design Bird Chandelier Led Light for Dinning & kitchen',
    description: 'Artistic bird-themed chandelier, ideal for dining areas and modern kitchens.',
    price: 75000,
    imageId: 'prod-19',
    category: 'Chandelier',
  },
  {
    id: 'prod-20',
    name: 'New Design Crystal Drop Light',
    description: 'A fresh, new design in crystal drop lighting for modern interiors.',
    price: 75000,
    imageId: 'prod-20',
    category: 'Pendant Light',
  },
  {
    id: 'prod-21',
    name: 'New Luxury Crystal Gold Duplex Chandelier',
    description: 'Grand luxury gold duplex chandelier featuring premium crystal accents.',
    price: 350000,
    imageId: 'prod-21',
    category: 'Chandelier',
  },
  {
    id: 'prod-22',
    name: 'New Unique Design Led Light',
    description: 'A unique LED lighting solution with a cutting-edge design.',
    price: 120000,
    imageId: 'prod-22',
    category: 'Pendant Light',
  },
  {
    id: 'prod-23',
    name: 'Nodic Modern Creative Feather wall bracket',
    description: 'Nordic-inspired creative wall bracket with a delicate feather design.',
    price: 15000,
    imageId: 'prod-23',
    category: 'Wall Light',
  },
  {
    id: 'prod-24',
    name: 'Nodic Modern Creative Feather wall Ligh',
    description: 'Artistic Nordic wall light featuring a stunning creative feather motif.',
    price: 20000,
    imageId: 'prod-24',
    category: 'Wall Light',
  },
  {
    id: 'prod-25',
    name: 'Pure crystal charming Chandelier Light',
    description: 'Charming chandelier crafted from pure crystals for maximum brilliance.',
    price: 400000,
    imageId: 'prod-25',
    category: 'Chandelier',
  },
  {
    id: 'prod-26',
    name: 'crafted to dazzle the perfect blend of modern design Chandelier Light',
    description: 'Exquisitely crafted chandelier that is the perfect blend of modern and dazzling design.',
    price: 190000,
    imageId: 'prod-26',
    category: 'Chandelier',
  },
  {
    id: 'prod-27',
    name: 'Unique 3Way Round Led Light',
    description: 'A unique 3-way round LED light for versatile illumination patterns.',
    price: 75000,
    imageId: 'prod-27',
    category: 'Pendant Light',
  },
  {
    id: 'prod-28',
    name: 'Unique 4 way Ball Led Drop Light',
    description: 'Creative 4-way ball LED drop light for a playful yet elegant look.',
    price: 80000,
    imageId: 'prod-28',
    category: 'Pendant Light',
  },
  {
    id: 'prod-29',
    name: 'Unique Butterfly Led Dropping Light',
    description: 'Enchanting butterfly-themed LED dropping light for magical spaces.',
    price: 120000,
    imageId: 'prod-29',
    category: 'Pendant Light',
  },
  {
    id: 'prod-30',
    name: 'Unique Decorative LED Chandelier',
    description: 'Decorative LED chandelier with a unique, eye-catching structure.',
    price: 220000,
    imageId: 'prod-30',
    category: 'Chandelier',
  },
  {
    id: 'prod-31',
    name: 'Unique Design 2 way Drop Light',
    description: 'Versatile 2-way LED drop light with a unique contemporary design.',
    price: 35000,
    imageId: 'prod-31',
    category: 'Pendant Light',
  },
  {
    id: 'prod-32',
    name: 'Unique Standing Led Lamp',
    description: 'Elegant standing LED lamp that makes a statement in any living space.',
    price: 95000,
    imageId: 'prod-32',
    category: 'Other Lighting',
  },
  {
    id: 'prod-33',
    name: 'Unique Track LED Drop Light',
    description: 'Industrial-inspired track LED light perfect for modern galleries and hallways.',
    price: 100000,
    imageId: 'prod-33',
    category: 'Pendant Light',
  },
  {
    id: 'prod-34',
    name: 'Unique Wall LED Light',
    description: 'Sculptural wall LED light that provides both illumination and artistic flair.',
    price: 19000,
    imageId: 'prod-34',
    category: 'Wall Light',
  },
  {
    id: 'prod-35',
    name: 'Wall bracket Light ',
    description: 'Simple yet elegant wall bracket light for cozy room ambiances.',
    price: 8000,
    imageId: 'prod-35',
    category: 'Wall Light',
  },
  {
    id: 'prod-36',
    name: 'Wall bracket light',
    description: 'Durable and stylish wall bracket lighting solution for your home.',
    price: 19000,
    imageId: 'prod-36',
    category: 'Wall Light',
  },
];
