import type { Product } from './types';

export const products: Product[] = [
  // BEDROOM COLLECTION
  {
    id: 'classic-damask-accent',
    name: 'Classic Damask Accent',
    description: 'A sophisticated accent piece featuring intricate damask patterns, designed to bring a touch of timeless elegance to your bedroom sanctuary.',
    price: 600000,
    originalPrice: 1500000,
    images: ['/images/products/Bedroom/classic-damask-accent-600000.avif'],
    category: 'Bedroom',
    material: 'Premium Fabric & Wood',
    stock: 4,
    rating: 4.8,
    reviews: 5
  },
  {
    id: 'comfortable-and-stylish-bed',
    name: 'Comfortable and Stylish Bed',
    description: 'Experience ultimate relaxation with this architecturally designed bed frame, blending modern silhouettes with unparalleled comfort.',
    price: 850000,
    originalPrice: 2250000,
    images: ['/images/products/Bedroom/comfortable-and-stylish-bed-850000.avif'],
    category: 'Bedroom',
    material: 'Upholstered Velvet',
    dimensions: 'King Size',
    stock: 3,
    rating: 5.0,
    reviews: 12
  },
  {
    id: 'green-curvette',
    name: 'Green Curvette',
    description: 'An avant-garde seating solution for the modern bedroom, featuring fluid curves and a rich emerald finish.',
    price: 600000,
    originalPrice: 1350000,
    images: ['/images/products/Bedroom/green-curvette-600000.avif'],
    category: 'Bedroom',
    material: 'High-density Foam & Premium Textile',
    stock: 2,
    rating: 4.9,
    reviews: 3
  },
  {
    id: 'machiatto-set',
    name: 'Machiatto Set',
    description: 'A curated ensemble of bedroom furniture that balances warm tones with contemporary lines for a distinguished look.',
    price: 600000,
    originalPrice: 1450000,
    images: ['/images/products/Bedroom/machiatto-set-600000.avif'],
    category: 'Bedroom',
    material: 'Polished Wood & Metal Accents',
    stock: 5,
    rating: 4.7,
    reviews: 8
  },
  {
    id: 'rocky-set',
    name: 'Rocky Set',
    description: 'Robust yet refined, the Rocky set provides a grounded aesthetic to any luxury interior with its textured finishes and solid build.',
    price: 600000,
    originalPrice: 1250000,
    images: ['/images/products/Bedroom/rocky-set-600000.avif'],
    category: 'Bedroom',
    material: 'Industrial Grade Materials',
    stock: 3,
    rating: 4.6,
    reviews: 6
  },
  {
    id: 'varta-console',
    name: 'Varta Console',
    description: 'A masterpiece of minimalism, the Varta console serves as a perfect vanity or display surface in high-end bedroom suites.',
    price: 800000,
    originalPrice: 1850000,
    images: ['/images/products/Bedroom/varta-console-800000.avif'],
    category: 'Bedroom',
    material: 'Marble & Gold-finished Steel',
    stock: 2,
    rating: 4.9,
    reviews: 10
  },
  {
    id: 'wardrobe-with-inbuilt-light',
    name: 'Wardrobe with Inbuilt Light',
    description: 'Intelligent storage meets architectural lighting. This wardrobe features sensor-activated internal illumination and premium shelving.',
    price: 950000,
    originalPrice: 2450000,
    images: ['/images/products/Bedroom/wardrobe-with-inbuilt-light-950000.avif'],
    category: 'Bedroom',
    material: 'High-gloss Finish & Integrated LED',
    dimensions: '240cm x 200cm x 60cm',
    stock: 2,
    rating: 5.0,
    reviews: 15
  },

  // BULBS COLLECTION
  {
    id: 'akt-5w-bulb',
    name: 'AKT 5W LED Bulb',
    description: 'High-efficiency 5W LED bulb from AKT, providing crisp illumination while maintaining low energy consumption.',
    price: 900,
    originalPrice: 4500,
    images: ['/images/products/Bulbs/akt-5w-bulb-900.avif'],
    category: 'Bulbs',
    stock: 50,
    rating: 4.8,
    reviews: 24
  },
  {
    id: 'akt-15w-bulb',
    name: 'AKT 15W High Power Bulb',
    description: 'Powerful 15W AKT LED bulb designed for larger spaces. Delivers bright, consistent light.',
    price: 1700,
    originalPrice: 8500,
    images: ['/images/products/Bulbs/akt-15w-bulb-1700.avif'],
    category: 'Bulbs',
    stock: 40,
    rating: 4.7,
    reviews: 18
  },
  {
    id: 'akt-18w-pop-bulb',
    name: 'AKT 18W POP Integrated Bulb',
    description: 'Specialized 18W bulb optimized for POP ceiling installations. Features a wide beam angle.',
    price: 3800,
    originalPrice: 15500,
    images: ['/images/products/Bulbs/akt-18w-pop-bulb-3800.avif'],
    category: 'Bulbs',
    stock: 30,
    rating: 4.9,
    reviews: 12
  },
  {
    id: 'dli-10w-bulb',
    name: 'DLI 10W Energy Efficient Bulb',
    description: 'DLI 10W LED bulb offering a perfect balance of brightness and power efficiency.',
    price: 900,
    originalPrice: 4500,
    images: ['/images/products/Bulbs/dli-10w-bulb-900.avif'],
    category: 'Bulbs',
    stock: 60,
    rating: 4.6,
    reviews: 32
  },

  // CEILING & POP LIGHTING
  {
    id: 'track-light-20w',
    name: '20W Track Light',
    description: 'Sleek and versatile 20W track light providing focused architectural illumination.',
    price: 7000,
    originalPrice: 35000,
    images: ['/images/products/Ceiling-&-Pop-Lighting/20w-track-light-7000.avif'],
    category: 'Ceiling & Pop Lighting',
    stock: 25,
    rating: 4.8,
    reviews: 9
  },
  {
    id: 'track-light-40w',
    name: '40W Track Light',
    description: 'High-output 40W track lighting solution for grand living spaces.',
    price: 10000,
    originalPrice: 45000,
    images: ['/images/products/Ceiling-&-Pop-Lighting/40w-track-light-10000.avif'],
    category: 'Ceiling & Pop Lighting',
    stock: 15,
    rating: 4.9,
    reviews: 14
  },
  {
    id: 'bluetooth-pop-light',
    name: 'Bluetooth POP Light',
    description: 'Smart ceiling lighting with Bluetooth connectivity for mood control.',
    price: 55000,
    originalPrice: 165000,
    images: ['/images/products/Ceiling-&-Pop-Lighting/bluetooth-pop-light-55000.avif'],
    category: 'Ceiling & Pop Lighting',
    stock: 10,
    rating: 5.0,
    reviews: 21
  },
  {
    id: 'decorative-pop-light',
    name: 'Decorative POP Light',
    description: 'Intricately designed POP light fixture that serves as a stunning focal point.',
    price: 60000,
    originalPrice: 185000,
    images: ['/images/products/Ceiling-&-Pop-Lighting/decorative-pop-light-60000.avif'],
    category: 'Ceiling & Pop Lighting',
    stock: 8,
    rating: 4.7,
    reviews: 7
  },
  {
    id: 'design-pop-light',
    name: 'Design POP Light',
    description: 'Designer-grade ceiling light offering architectural beauty.',
    price: 70000,
    originalPrice: 215000,
    images: ['/images/products/Ceiling-&-Pop-Lighting/design-pop-light-70000.avif'],
    category: 'Ceiling & Pop Lighting',
    stock: 6,
    rating: 4.9,
    reviews: 11
  },
  {
    id: 'okeli-rope-light',
    name: 'Okeli Rope Light',
    description: 'Premium Okeli rope lighting for hidden ceiling accents.',
    price: 40000,
    originalPrice: 115000,
    images: ['/images/products/Ceiling-&-Pop-Lighting/okeli-rope-light-40000.avif'],
    category: 'Ceiling & Pop Lighting',
    stock: 12,
    rating: 4.8,
    reviews: 18
  },
  {
    id: 'pop-decorative-light',
    name: 'POP Decorative Light Premium',
    description: 'A masterpiece of ceiling illumination, combining modern tech with traditional aesthetics.',
    price: 70000,
    originalPrice: 195000,
    images: ['/images/products/Ceiling-&-Pop-Lighting/pop-decorative-light-70000.avif'],
    category: 'Ceiling & Pop Lighting',
    stock: 5,
    rating: 5.0,
    reviews: 13
  },
  {
    id: '7w-pop-light',
    name: '7W POP Light',
    description: 'Energy-efficient 7W POP ceiling light offering sharp, refined illumination for recessed ceiling patterns.',
    price: 4500,
    originalPrice: 12000,
    images: ['/images/products/Ceiling-&-Pop-Lighting/7w-pop-light-4500_result.avif'],
    category: 'Ceiling & Pop Lighting',
    stock: 30,
    rating: 4.8,
    reviews: 14
  },
  {
    id: 'pop-double-light',
    name: 'POP Double Light',
    description: 'Dual-source recessed POP ceiling light designed for balanced ambiance and enhanced illumination in contemporary spaces.',
    price: 6000,
    originalPrice: 15000,
    images: ['/images/products/Ceiling-&-Pop-Lighting/pop-double-light-6000_result.avif'],
    category: 'Ceiling & Pop Lighting',
    stock: 25,
    rating: 4.9,
    reviews: 16
  },
  {
    id: 'modern-fan-ac-led-light',
    name: 'Modern Fan AC LED Ceiling Light',
    description: 'State-of-the-art integrated fan and AC LED ceiling light fixture combining whisper-quiet airflow with radiant dimmable illumination.',
    price: 150000,
    originalPrice: 320000,
    images: ['/images/products/Ceiling-&-Pop-Lighting/modern-fan-ac-led-light-150000_result.avif'],
    category: 'Ceiling & Pop Lighting',
    stock: 8,
    rating: 5.0,
    reviews: 22
  },
  {
    id: 'stylish-led-ceiling-pop-light',
    name: 'Stylish LED Ceiling POP Light',
    description: 'Architectural luxury ceiling light crafted with premium geometric LED elements for prestigious living areas.',
    price: 150000,
    originalPrice: 300000,
    images: ['/images/products/Ceiling-&-Pop-Lighting/stylish-led-ceiling-pop-light-150000_result.avif'],
    category: 'Ceiling & Pop Lighting',
    stock: 6,
    rating: 4.9,
    reviews: 19
  },
  {
    id: 'ring-led-light',
    name: 'Ring LED Ceiling Light',
    description: 'Minimalist halo ring ceiling fixture delivering 360-degree diffused lighting with sleek modern aesthetics.',
    price: 70000,
    originalPrice: 160000,
    images: ['/images/products/Ceiling-&-Pop-Lighting/ring-led-light-70000_result.avif'],
    category: 'Ceiling & Pop Lighting',
    stock: 12,
    rating: 4.8,
    reviews: 11
  },

  // CHANDELIER LIGHTING COLLECTION
  {
    id: 'crystal-chandelier-410',
    name: 'Crystal Chandelier',
    description: 'A grand crystal chandelier offering timeless elegance and brilliant illumination.',
    price: 410000,
    originalPrice: 950000,
    images: ['/images/products/Chandelier-Lighting/crystal-chandelier-410000-sold-out.avif'],
    category: 'Chandelier Lighting',
    isSoldOut: true,
    rating: 4.9,
    reviews: 10
  },
  {
    id: 'crystal-fan-bluetooth',
    name: 'Crystal Fan Chandelier with Bluetooth',
    description: 'Multi-functional luxury featuring an integrated fan and Bluetooth smart control.',
    price: 180000,
    originalPrice: 420000,
    images: ['/images/products/Chandelier-Lighting/crystal-fan-chandelier-with-bluetooth-180000.avif'],
    category: 'Chandelier Lighting',
    rating: 4.8,
    reviews: 15
  },
  {
    id: 'decorative-crystal-chandelier',
    name: 'Decorative Crystal Chandelier',
    description: 'Intricately crafted crystals designed to refract light into a spectral masterpiece.',
    price: 400000,
    originalPrice: 920000,
    images: ['/images/products/Chandelier-Lighting/decorative-crystal-chandelier-400000.avif'],
    category: 'Chandelier Lighting',
    rating: 5.0,
    reviews: 8
  },
  {
    id: 'elegant-modern-crystal',
    name: 'Elegant and Modern Crystal Chandelier',
    description: 'A minimalist interpretation of classic crystal lighting for modern residences.',
    price: 150000,
    originalPrice: 385000,
    images: ['/images/products/Chandelier-Lighting/elegant-and-modern-crystal-chandelier-150000.avif'],
    category: 'Chandelier Lighting',
    rating: 4.7,
    reviews: 22
  },
  {
    id: 'luxurious-royal-crystal',
    name: 'Luxurious Royal Crystal Chandelier',
    description: 'The pinnacle of luxury. A grand-scale royal design for high-ceiling ballrooms and entryways.',
    price: 800000,
    originalPrice: 1850000,
    images: ['/images/products/Chandelier-Lighting/luxurious-royal-crystal-chandelier-800000.avif'],
    category: 'Chandelier Lighting',
    rating: 5.0,
    reviews: 31
  },
  {
    id: 'luxury-crystal-gold-duplex',
    name: 'Luxury Crystal Gold Duplex Chandelier',
    description: 'Stunning gold-finished structure paired with premium K9 crystals for duplex spaces.',
    price: 350000,
    originalPrice: 750000,
    images: ['/images/products/Chandelier-Lighting/luxury-crystal-gold-duplex-chandelier-350000.avif'],
    category: 'Chandelier Lighting',
    rating: 4.9,
    reviews: 14
  },
  {
    id: 'luxury-led-ceiling-chandelier',
    name: 'Luxury LED Ceiling Chandelier',
    description: 'Integrated high-output LEDs combined with decorative crystal elements.',
    price: 250000,
    originalPrice: 585000,
    images: ['/images/products/Chandelier-Lighting/luxury-led-ceiling-chandelier-250000.avif'],
    category: 'Chandelier Lighting',
    rating: 4.8,
    reviews: 19
  },
  {
    id: 'luxury-vintage-crystal',
    name: 'Luxury Vintage Crystal Chandelier',
    description: 'A classic silhouette that evokes the glamour of traditional European estates.',
    price: 280000,
    originalPrice: 650000,
    images: ['/images/products/Chandelier-Lighting/luxury-vintage-crystal-chandelier-280000.avif'],
    category: 'Chandelier Lighting',
    rating: 4.7,
    reviews: 11
  },
  {
    id: 'modern-led-crystal-190',
    name: 'Modern LED Crystal Chandelier (Size 500)',
    description: 'Sophisticated lighting solution with high-efficiency LED chips.',
    price: 190000,
    originalPrice: 420000,
    images: ['/images/products/Chandelier-Lighting/modern-led-crystal-chandelier-size-500-190000.avif'],
    category: 'Chandelier Lighting',
    rating: 5.0,
    reviews: 7
  },
  {
    id: 'modern-crystal-chandelier-sold',
    name: 'Modern Crystal Chandelier',
    description: 'Sleek architectural lines meets brilliant crystal craftsmanship.',
    price: 180000,
    originalPrice: 410000,
    images: ['/images/products/Chandelier-Lighting/modern-crystal-chandelier-180,000-sold-out.avif'],
    category: 'Chandelier Lighting',
    isSoldOut: true,
    rating: 4.8,
    reviews: 12
  },
  {
    id: 'modern-crystal-light-400',
    name: 'Modern Crystal Chandelier Light (Size 400)',
    description: 'Compact yet brilliant, perfect for dining areas or luxury master bedrooms.',
    price: 120000,
    originalPrice: 285000,
    images: ['/images/products/Chandelier-Lighting/modern-crystal-chandelier-light-120000-size-400.avif'],
    category: 'Chandelier Lighting',
    rating: 4.9,
    reviews: 25
  },
  {
    id: 'modern-decorative-crystal-chandelier-light-190000',
    name: 'Modern Decorative Crystal Chandelier Light',
    description: 'An artistic lighting fixture that serves as both a light source and a sculpture.',
    price: 190000,
    originalPrice: 445000,
    images: ['/images/products/Chandelier-Lighting/modern-decorative-crystal-chandelier-light-190000.avif'],
    category: 'Chandelier Lighting',
    rating: 4.9,
    reviews: 16
  },
  {
    id: 'modern-design-crystal-chandelier-size-500-180000',
    name: 'Modern Design Crystal Chandelier (Size 500)',
    description: 'Precision engineered for the modern home, featuring balanced light distribution.',
    price: 180000,
    originalPrice: 425000,
    images: ['/images/products/Chandelier-Lighting/modern-design-crystal-chandelier-size-500-180000.avif'],
    category: 'Chandelier Lighting',
    rating: 4.8,
    reviews: 9
  },
  {
    id: 'modern-led-crystal-chandelier-160000-size-500',
    name: 'Modern LED Crystal Chandelier (Size 500)',
    description: 'Energy efficient LED technology integrated into a luxury crystal frame.',
    price: 160000,
    originalPrice: 385000,
    images: ['/images/products/Chandelier-Lighting/modern-led-crystal-chandelier-160000-size-500.avif'],
    category: 'Chandelier Lighting',
    rating: 4.7,
    reviews: 13
  },
  {
    id: 'modern-led-crystal-chandelier-220000-size-600',
    name: 'Modern LED Crystal Chandelier (Size 600)',
    description: 'Larger format LED chandelier designed for grand dining spaces.',
    price: 220000,
    originalPrice: 495000,
    images: ['/images/products/Chandelier-Lighting/modern-led-crystal-chandelier-220000-size-600.avif'],
    category: 'Chandelier Lighting',
    rating: 4.9,
    reviews: 21
  },
  {
    id: 'modern-luxury-nordic-rain-drop-light-300000',
    name: 'Modern Luxury Nordic Rain Drop Light',
    description: 'Artistic "Rain Drop" design featuring cascading crystals for a dramatic effect.',
    price: 300000,
    originalPrice: 650000,
    images: ['/images/products/Chandelier-Lighting/modern-luxury-nordic-rain-drop-light-300000.avif'],
    category: 'Chandelier Lighting',
    rating: 4.9,
    reviews: 18
  },
  {
    id: 'modern-round-crystal-chandelier-350000',
    name: 'Modern Round Crystal Chandelier',
    description: 'Circular architectural frame adorned with premium hand-cut crystals.',
    price: 350000,
    originalPrice: 725000,
    images: ['/images/products/Chandelier-Lighting/modern-round-crystal-chandelier-350000.avif'],
    category: 'Chandelier Lighting',
    rating: 5.0,
    reviews: 14
  },
  {
    id: 'new-luxury-crystal-gold-duplex-chandelier-380000',
    name: 'New Luxury Crystal Gold Duplex Chandelier',
    description: 'The latest addition to our collection, featuring an enhanced gold finish and high-quality crystals.',
    price: 380000,
    originalPrice: 780000,
    images: ['/images/products/Chandelier-Lighting/new-luxury-crystal-gold-duplex-chandelier-380000.avif'],
    category: 'Chandelier Lighting',
    rating: 4.8,
    reviews: 5
  },
  {
    id: 'pure-crystal-charming-chandelier-light-400000',
    name: 'Pure Crystal Charming Chandelier Light',
    description: 'Radiates charm and brilliance, designed to be the crown of any room.',
    price: 400000,
    originalPrice: 820000,
    images: ['/images/products/Chandelier-Lighting/pure-crystal-charming-chandelier-light-400000.avif'],
    category: 'Chandelier Lighting',
    rating: 4.9,
    reviews: 20
  },
  {
    id: 'stylish-crystal-chandelier-size-500-160000',
    name: 'Stylish Crystal Chandelier (Size 500)',
    description: 'Fashion-forward lighting design for distinguished interiors.',
    price: 160000,
    originalPrice: 395000,
    images: ['/images/products/Chandelier-Lighting/stylish-crystal-chandelier-size-500-160000.avif'],
    category: 'Chandelier Lighting',
    rating: 4.7,
    reviews: 11
  },
  {
    id: 'unique-decorative-led-chandelier-220000',
    name: 'Unique Decorative LED Chandelier',
    description: 'One-of-a-kind LED structure that blends modern technology with avant-garde design.',
    price: 220000,
    originalPrice: 485000,
    images: ['/images/products/Chandelier-Lighting/unique-decorative-led-chandelier-220000.avif'],
    category: 'Chandelier Lighting',
    rating: 4.8,
    reviews: 15
  },
  {
    id: 'unique-high-quality-crystal-chandelier-280000',
    name: 'Unique High Quality Crystal Chandelier',
    description: 'Exceptional craftsmanship and the highest grade crystals for discerning homeowners.',
    price: 280000,
    originalPrice: 595000,
    images: ['/images/products/Chandelier-Lighting/unique-high-quality-crystal-chandelier-280000.avif'],
    category: 'Chandelier Lighting',
    rating: 4.9,
    reviews: 23
  },
  {
    id: 'unique-nordic-rain-led-drop-light-400000',
    name: 'Unique Nordic Rain LED Drop Light',
    description: 'Sophisticated LED drop lighting that creates a calming, luxurious atmosphere.',
    price: 400000,
    originalPrice: 825000,
    images: ['/images/products/Chandelier-Lighting/unique-nordic-rain-led-drop-light-400000.avif'],
    category: 'Chandelier Lighting',
    rating: 5.0,
    reviews: 29
  },
  {
    id: 'modern-leaf-crystal-chandelier-size-800',
    name: 'Modern Leaf Crystal Chandelier (Size 800)',
    description: 'Organic botanical inspired crystal chandelier featuring precision-cut crystal leaves, included bulbs, and an 800mm diameter.',
    price: 350000,
    originalPrice: 750000,
    images: ['/images/products/Chandelier-Lighting/modern-leaf-crystal-chandelier-with-bulb-size-800-350000_result.avif'],
    category: 'Chandelier Lighting',
    stock: 4,
    rating: 5.0,
    reviews: 8
  },
  {
    id: 'modern-stylish-crystal-chandelier-creative-designs',
    name: 'Modern Stylish Crystal Chandelier (Creative Design)',
    description: 'Avant-garde statement chandelier showcasing creative artistic crystal craftsmanship and multi-tiered illumination.',
    price: 450000,
    originalPrice: 980000,
    images: ['/images/products/Chandelier-Lighting/modern-stylish-crystal-chandelier-made-with-creative-designs-450000_result.avif'],
    category: 'Chandelier Lighting',
    stock: 3,
    rating: 5.0,
    reviews: 12
  },
  {
    id: 'crystal-modern-ring-tiered-gold-branch-chandelier',
    name: 'Crystal Modern Ring Tiered Gold & Branch Chandelier',
    description: 'Exquisite fusion of tiered golden rings and organic branch crystal motifs, creating a majestic centerpiece.',
    price: 350000,
    originalPrice: 750000,
    images: ['/images/products/Chandelier-Lighting/crystal-modern-ring-tiered-gold-and-branch-style-chandelier-350000_result.avif'],
    category: 'Chandelier Lighting',
    stock: 5,
    rating: 4.9,
    reviews: 15
  },
  {
    id: 'luxurious-tiered-crystal-chandelier',
    name: 'Luxurious Tiered Crystal Chandelier',
    description: 'Cascading multi-tiered crystal prisms suspended from a radiant frame, reflecting light into dazzling diamond patterns.',
    price: 200000,
    originalPrice: 450000,
    images: ['/images/products/Chandelier-Lighting/luxurious-tiered-crystal-chandelier-200000_result.avif'],
    category: 'Chandelier Lighting',
    stock: 6,
    rating: 4.8,
    reviews: 11
  },
  {
    id: 'modern-crystal-drum-chandelier',
    name: 'Modern Crystal Drum Chandelier',
    description: 'Contemporary cylindrical drum chandelier wrapped in shimmering crystals for sleek dining and living space aesthetics.',
    price: 70000,
    originalPrice: 160000,
    images: ['/images/products/Chandelier-Lighting/modern-crystal-drum-chandelier-70,000_result.avif'],
    category: 'Chandelier Lighting',
    stock: 7,
    rating: 4.8,
    reviews: 9
  },
  {
    id: 'unique-crystal-led-chandelier-size-300',
    name: 'Unique Crystal LED Chandelier (Size 300)',
    description: 'Compact 300mm designer crystal LED chandelier with precision crystal cuts, perfect for master suites and intimate dining.',
    price: 120000,
    originalPrice: 260000,
    images: ['/images/products/Chandelier-Lighting/unique-crystal-led-chandelier-size-300-120000_result.avif'],
    category: 'Chandelier Lighting',
    stock: 8,
    rating: 4.9,
    reviews: 10
  },
  {
    id: 'unique-crystal-led-chandelier-size-500',
    name: 'Unique Crystal LED Chandelier (Size 500)',
    description: 'Grand 500mm crystal LED chandelier offering luminous presence and multi-angle radiance for luxurious interiors.',
    price: 180000,
    originalPrice: 390000,
    images: ['/images/products/Chandelier-Lighting/unique-crystal-led-chandelier-size-500-180000_result.avif'],
    category: 'Chandelier Lighting',
    stock: 6,
    rating: 5.0,
    reviews: 14
  },
  {
    id: 'moon-nordic-crystal-chandelier',
    name: 'Moon Nordic Crystal Chandelier',
    description: 'Scandinavian moon-inspired crystal chandelier casting a warm, romantic lunar glow across modern rooms.',
    price: 65000,
    originalPrice: 150000,
    images: ['/images/products/Chandelier-Lighting/moon-nordic-crystal-chandelier-65000_result.avif'],
    category: 'Chandelier Lighting',
    stock: 10,
    rating: 4.8,
    reviews: 13
  },
  {
    id: 'luxury-gold-ring-chandelier',
    name: 'Luxury Gold Ring Chandelier',
    description: 'Minimalist interlocking gold circular rings embedded with high-lumen LEDs for an upscale modern look.',
    price: 110000,
    originalPrice: 240000,
    images: ['/images/products/Chandelier-Lighting/luxury-gold-ring-chandelier-110000_result.avif'],
    category: 'Chandelier Lighting',
    stock: 7,
    rating: 4.9,
    reviews: 16
  },
  {
    id: 'stunning-gold-crystal-chandelier',
    name: 'Stunning Gold Crystal Chandelier',
    description: 'Dazzling gold finish chandelier trimmed with optical K9 crystals for regal opulence and high-end elegance.',
    price: 150000,
    originalPrice: 330000,
    images: ['/images/products/Chandelier-Lighting/stunning-gold-crystal-chandelier-150000_result.avif'],
    category: 'Chandelier Lighting',
    stock: 5,
    rating: 5.0,
    reviews: 18
  },

  // DINING SET COLLECTION
  {
    id: 'six-seater-grey-italian-bursa',
    name: '6 Seater Grey Italian Bursa Dining Set',
    description: 'A masterpiece of Italian design, featuring a 6-seater configuration with plush grey upholstery and a sophisticated bursa finish.',
    price: 1500000,
    originalPrice: 3500000,
    images: ['/images/products/Dining-Set/6-seater-grey-italian-bursa-1500000.avif'],
    category: 'Dining Set',
    material: 'Italian Fabric & Premium Wood',
    dimensions: '6 Seater',
    stock: 2,
    rating: 5.0,
    reviews: 6
  },

  // HOUSE DECORATIVES COLLECTION
  {
    id: 'antelope-deer-decor',
    name: 'Antelope Deer Decor',
    description: 'An elegant antelope deer sculpture, meticulously crafted to add a touch of nature-inspired luxury to your living space.',
    price: 150000,
    originalPrice: 350000,
    images: ['/images/products/House-Decoratives/antelope-deer-decor-150000.avif'],
    category: 'House Decoratives',
    material: 'Gold-finished Metal',
    stock: 5,
    rating: 4.8,
    reviews: 4
  },
  {
    id: 'candle-dinning-lamp-set',
    name: 'Candle Dining Lamp Set',
    description: 'Create an ambient atmosphere with this sophisticated candle lamp set, perfect for illuminating intimate dining experiences.',
    price: 300000,
    originalPrice: 650000,
    images: ['/images/products/House-Decoratives/candle-dinning-lamp-set-300000.avif'],
    category: 'House Decoratives',
    material: 'Crystal & Polished Chrome',
    stock: 3,
    rating: 5.0,
    reviews: 7
  },
  {
    id: 'clock-globe',
    name: 'Clock Globe',
    description: 'A striking fusion of timekeeping and cartography, this clock globe is a distinguished addition to any professional office or library.',
    price: 120000,
    originalPrice: 285000,
    images: ['/images/products/House-Decoratives/clock-gobe-120000.avif'],
    category: 'House Decoratives',
    material: 'Brass & Walnut',
    stock: 6,
    rating: 4.7,
    reviews: 9
  },
  {
    id: 'medium-size-deer-decor',
    name: 'Medium Size Deer Decor',
    description: 'Graceful deer statuette that serves as a subtle yet impactful focal point for modern sideboards and consoles.',
    price: 120000,
    originalPrice: 250000,
    images: ['/images/products/House-Decoratives/medium-size-deer-decor-120000.avif'],
    category: 'House Decoratives',
    stock: 4,
    rating: 4.9,
    reviews: 3
  },
  {
    id: 'round-side-table',
    name: 'Round Side Table',
    description: 'Minimalist round side table crafted for both utility and aesthetic appeal in high-end residential interiors.',
    price: 100000,
    originalPrice: 225000,
    images: ['/images/products/House-Decoratives/round-side-table-100000.avif'],
    category: 'House Decoratives',
    material: 'Marble & Metal',
    stock: 8,
    rating: 4.8,
    reviews: 12
  },
  {
    id: 'small-deer-decor',
    name: 'Small Deer Decor',
    description: 'Compact deer figurine, perfect for adding a luxurious touch to bookshelves or bedside tables.',
    price: 100000,
    originalPrice: 195000,
    images: ['/images/products/House-Decoratives/small-deer-decor-100000.avif'],
    category: 'House Decoratives',
    stock: 10,
    rating: 4.7,
    reviews: 6
  },
  {
    id: 'small-tree-decor',
    name: 'Small Tree Decor',
    description: 'An architectural representation of nature, this small tree decor brings balance and serenity to your decor scheme.',
    price: 100000,
    originalPrice: 195000,
    images: ['/images/products/House-Decoratives/small-tree-decor-100000.avif'],
    category: 'House Decoratives',
    stock: 7,
    rating: 4.6,
    reviews: 5
  },
  {
    id: 'snow-flower-set',
    name: 'Snow Flower Set',
    description: 'Delicate floral sculpture set that captures the ethereal beauty of winter blooms in a permanent luxury form.',
    price: 170000,
    originalPrice: 325000,
    images: ['/images/products/House-Decoratives/snow-flower-set-170000.avif'],
    category: 'House Decoratives',
    material: 'Ceramic & Glass',
    stock: 4,
    rating: 4.9,
    reviews: 8
  },
  {
    id: 'standing-horse-gold-decor',
    name: 'Standing Horse Gold Decor',
    description: 'A symbol of strength and prestige, this gold-finished standing horse is a bold statement piece for the discerning home.',
    price: 150000,
    originalPrice: 325000,
    images: ['/images/products/House-Decoratives/standing-horse-gold-decor-150000.avif'],
    category: 'House Decoratives',
    material: 'Gold-plated Resin',
    stock: 3,
    rating: 5.0,
    reviews: 11
  },
  {
    id: 'stoned-frame',
    name: 'Stoned Frame',
    description: 'Artistic frame featuring natural stone textures, designed to showcase your most precious memories in architectural style.',
    price: 200000,
    originalPrice: 425000,
    images: ['/images/products/House-Decoratives/stoned-frame-200000.avif'],
    category: 'House Decoratives',
    material: 'Natural Stone & Glass',
    stock: 5,
    rating: 4.8,
    reviews: 4
  },
  {
    id: 'triangle-clock-decor',
    name: 'Triangle Clock Decor',
    description: 'Geometric precision meets timeless design. This triangular clock is an avant-garde timekeeping solution for modern desks.',
    price: 120000,
    originalPrice: 245000,
    images: ['/images/products/House-Decoratives/triangle-clock-decor-120000.avif'],
    category: 'House Decoratives',
    stock: 6,
    rating: 4.7,
    reviews: 7
  },
  {
    id: 'wall-decor',
    name: 'Wall Decor',
    description: 'Bespoke wall-mounted sculpture that adds depth and texture to large living room surfaces.',
    price: 150000,
    originalPrice: 325000,
    images: ['/images/products/House-Decoratives/wall-decor-150000.avif'],
    category: 'House Decoratives',
    stock: 4,
    rating: 4.9,
    reviews: 10
  },
  {
    id: 'wall-design-mirror',
    name: 'Wall Design Mirror',
    description: 'An architectural mirror featuring a unique designer frame, designed to expand the light and space within your sanctuary.',
    price: 340000,
    originalPrice: 685000,
    images: ['/images/products/House-Decoratives/wall-design-mirror-340000.avif'],
    category: 'House Decoratives',
    material: 'Premium Glass & Silver Finish',
    stock: 2,
    rating: 5.0,
    reviews: 14
  },
  {
    id: 'white-fur-light',
    name: 'White Fur Light',
    description: 'A tactile lighting experience, this white fur lamp provides a soft, diffused glow for a cozy yet high-end atmosphere.',
    price: 150000,
    originalPrice: 285000,
    images: ['/images/products/House-Decoratives/white-fur-light-150000.avif'],
    category: 'House Decoratives',
    material: 'Faux Fur & LED',
    stock: 5,
    rating: 4.8,
    reviews: 6
  },

  // LIVING ROOM COLLECTION
  {
    id: 'armani-cassa-set',
    name: 'Armani Cassa Sofa Set',
    description: 'A cinematic seating ensemble inspired by modern architectural silhouettes, featuring premium upholstery and superior structural integrity.',
    price: 2500000,
    originalPrice: 5500000,
    images: ['/images/products/Living-Room/armani-cassa-set-2500000.avif'],
    category: 'Living Room',
    material: 'Italian Textile & Solid Core Frame',
    stock: 2,
    rating: 5.0,
    reviews: 18
  },
  {
    id: 'chocolate-center-table',
    name: 'Chocolate Center Table',
    description: 'A sophisticated coffee table with a rich chocolate finish, designed to anchor your living space with warmth and modern elegance.',
    price: 500000,
    originalPrice: 1250000,
    images: ['/images/products/Living-Room/chocolate-center-table-500000.avif'],
    category: 'Living Room',
    material: 'Polished Hardwood & Glass Accent',
    stock: 4,
    rating: 4.8,
    reviews: 9
  },
  {
    id: 'fehdi-console',
    name: 'Fehdi Console',
    description: 'An avant-garde console table that serves as a perfect gallery surface for your most prized decoratives.',
    price: 650000,
    originalPrice: 1450000,
    images: ['/images/products/Living-Room/fehdi-console-650000.avif'],
    category: 'Living Room',
    material: 'Brushed Metal & Marble Top',
    stock: 3,
    rating: 4.9,
    reviews: 5
  },
  {
    id: 'fire-flame-tv-stand',
    name: 'Fire Flame TV Stand',
    description: 'Dramatic architectural TV console featuring clean lines and a finish that captures the play of light across its surfaces.',
    price: 300000,
    originalPrice: 750000,
    images: ['/images/products/Living-Room/fire-flame-tv-stand-300000.avif'],
    category: 'Living Room',
    material: 'Engineered Wood & Tempered Glass',
    stock: 5,
    rating: 4.7,
    reviews: 12
  },
  {
    id: 'garrah-console',
    name: 'Garrah Console',
    description: 'Bold and distinguished, the Garrah console brings a sense of permanence and prestige to any entryway or living area.',
    price: 800000,
    originalPrice: 1850000,
    images: ['/images/products/Living-Room/garrah-console-800000.avif'],
    category: 'Living Room',
    material: 'Solid Walnut & Gold Leaf Details',
    stock: 2,
    rating: 5.0,
    reviews: 7
  },
  {
    id: 'osmo-sofa',
    name: 'Osmo Sofa',
    description: 'Ergonomic luxury redefined. The Osmo sofa features high-resilience foam and architectural tailoring for the modern sanctuary.',
    price: 2500000,
    originalPrice: 4800000,
    images: ['/images/products/Living-Room/osmo-sofa-2500000.avif'],
    category: 'Living Room',
    material: 'Premium Velvet & Steel Base',
    stock: 3,
    rating: 4.9,
    reviews: 14
  },
  {
    id: 'tufted-turkish-chairs-lr',
    name: 'Tufted Turkish Grand Chairs',
    description: 'Experience the pinnacle of Turkish craftsmanship. These hand-tufted chairs serve as royal statement pieces in any distinguished residence.',
    price: 8000000,
    originalPrice: 18000000,
    images: ['/images/products/Living-Room/tufted-turkish-chairs-8000000.avif'],
    category: 'Living Room',
    material: 'Hand-tufted Silk & Gold Leaf Wood',
    stock: 1,
    rating: 5.0,
    reviews: 4
  },
  {
    id: 'vitale-sofa-set',
    name: 'Vitale Sofa Set',
    description: 'A complete living room solution that balances comfort with a high-fashion aesthetic. Designed for hosting in style.',
    price: 3500000,
    originalPrice: 6850000,
    images: ['/images/products/Living-Room/vitale-sofa-set-3500000.avif'],
    category: 'Living Room',
    material: 'Performance Fabric & Titanium Accents',
    stock: 2,
    rating: 4.9,
    reviews: 21
  },

  // OFFICE COLLECTION
  {
    id: 'grey-executive-office-sofa',
    name: 'Grey Executive Office Sofa',
    description: 'A professional-grade sofa designed for executive lounges and high-end office reception areas, offering both comfort and corporate prestige.',
    price: 750000,
    originalPrice: 1550000,
    images: ['/images/products/Office/grey-sofa-750000.avif'],
    category: 'Office',
    material: 'High-grade Leather & Polished Steel',
    stock: 3,
    rating: 4.9,
    reviews: 5
  },

  // OUTDOOR LIGHTING COLLECTION
  {
    id: 'outdoor-light-8k-2',
    name: 'Outdoor Accent Light II',
    description: 'Durable and weather-resistant accent lighting for garden perimeters and pathway illumination.',
    price: 8000,
    originalPrice: 18000,
    images: ['/images/products/Outdoor-Lighting/circular-ambient-outdoor-light-8000.avif'],
    category: 'Outdoor Lighting',
    material: 'Anti-corrosive Alloy',
    stock: 15,
    rating: 4.7,
    reviews: 8
  },
  {
    id: 'outdoor-light-8k',
    name: 'Outdoor Accent Light I',
    description: 'Sleek exterior lighting solution designed to withstand harsh tropical conditions while providing a warm glow.',
    price: 8000,
    originalPrice: 18000,
    images: ['/images/products/Outdoor-Lighting/modern-slat-outdoor-wall-light-8000.avif'],
    category: 'Outdoor Lighting',
    material: 'Anti-corrosive Alloy',
    stock: 20,
    rating: 4.8,
    reviews: 12
  },
  {
    id: 'outdoor-light-11k',
    name: 'Modern Outdoor Wall Light',
    description: 'Contemporary wall-mounted exterior fixture, perfect for illuminating gates and building facades.',
    price: 11000,
    originalPrice: 25000,
    images: ['/images/products/Outdoor-Lighting/v-shape-designer-outdoor-light-11000.avif'],
    category: 'Outdoor Lighting',
    material: 'Tempered Glass & Metal',
    stock: 12,
    rating: 4.9,
    reviews: 6
  },
  {
    id: 'outdoor-light-12k',
    name: 'Architectural Exterior Light',
    description: 'Designed for high-end residential estates, providing powerful and directed architectural illumination.',
    price: 12000,
    originalPrice: 28000,
    images: ['/images/products/Outdoor-Lighting/modern-round-outdoor-sconce-12000.avif'],
    category: 'Outdoor Lighting',
    stock: 10,
    rating: 4.8,
    reviews: 4
  },
  {
    id: 'outdoor-light-17k',
    name: 'Premium Garden Path Light',
    description: 'High-output garden path light that combines energy efficiency with luxury aesthetic.',
    price: 17000,
    originalPrice: 42000,
    images: ['/images/products/Outdoor-Lighting/textured-linear-outdoor-light-17000.avif'],
    category: 'Outdoor Lighting',
    stock: 8,
    rating: 4.9,
    reviews: 9
  },
  {
    id: 'outdoor-light-18k',
    name: 'Deluxe Pillar Lighting',
    description: 'Stunning pillar-mounted light designed for estate entrances and grand driveways.',
    price: 18000,
    originalPrice: 45000,
    images: ['/images/products/Outdoor-Lighting/blue-accent-dual-outdoor-light-18000.avif'],
    category: 'Outdoor Lighting',
    stock: 6,
    rating: 5.0,
    reviews: 3
  },
  {
    id: 'outdoor-light-25k',
    name: 'Grand Estate Outdoor Light',
    description: 'A masterpiece of exterior design, featuring a robust frame and high-clarity diffuser.',
    price: 25000,
    originalPrice: 65000,
    images: ['/images/products/Outdoor-Lighting/classic-lantern-outdoor-wall-light-25000.avif'],
    category: 'Outdoor Lighting',
    stock: 5,
    rating: 4.9,
    reviews: 11
  },
  {
    id: 'outdoor-light-35k',
    name: 'Elite Landscape Illumination',
    description: 'The ultimate outdoor lighting solution for distinguished Lagos residences. Maximum durability and style.',
    price: 35000,
    originalPrice: 85000,
    images: ['/images/products/Outdoor-Lighting/premium-vintage-outdoor-lantern-35000.avif'],
    category: 'Outdoor Lighting',
    stock: 4,
    rating: 5.0,
    reviews: 15
  },
  {
    id: 'bulb-fence-light',
    name: 'Bulb Fence Light',
    description: 'Durable weather-sealed fence lighting fixture with classic bulb design for perimeter security and evening beauty.',
    price: 8000,
    originalPrice: 18000,
    images: ['/images/products/Outdoor-Lighting/bulb-fence-light-8000_result.avif'],
    category: 'Outdoor Lighting',
    stock: 20,
    rating: 4.7,
    reviews: 9
  },
  {
    id: 'led-fence-light',
    name: 'LED Fence Light',
    description: 'Architectural LED perimeter fence light providing downward illumination for luxury gateposts and boundary walls.',
    price: 9000,
    originalPrice: 20000,
    images: ['/images/products/Outdoor-Lighting/led-fence-light-9000_result.avif'],
    category: 'Outdoor Lighting',
    stock: 18,
    rating: 4.8,
    reviews: 13
  },
  {
    id: 'outdoor-led-light',
    name: 'Outdoor LED Light',
    description: 'Compact high-efficiency exterior LED fixture engineered for tropical weather resistance and pathway safety.',
    price: 4500,
    originalPrice: 12000,
    images: ['/images/products/Outdoor-Lighting/outdoor-led-light-4500_result.avif'],
    category: 'Outdoor Lighting',
    stock: 25,
    rating: 4.8,
    reviews: 15
  },
  {
    id: 'led-security-light',
    name: 'LED Security Light',
    description: 'High-intensity LED security wall luminaire offering ultra-wide perimeter coverage and all-weather resilience.',
    price: 4500,
    originalPrice: 12000,
    images: ['/images/products/Outdoor-Lighting/led-security-light-4500_result.avif'],
    category: 'Outdoor Lighting',
    stock: 30,
    rating: 4.9,
    reviews: 17
  },

  // PENDANT & DROP LIGHTING COLLECTION
  {
    id: '3-in-1-dropping-light',
    name: '3 in 1 Dropping Light',
    description: 'Elegant triple-source drop lighting for a modern dining or kitchen aesthetic.',
    price: 45000,
    originalPrice: 95000,
    images: ['/images/products/Pendant-&-Drop-Lighting/3-in-1-dropping-light-45000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 12,
    rating: 4.8,
    reviews: 7
  },
  {
    id: '5-in-1-dropping-light',
    name: '5 in 1 Dropping Light',
    description: 'A grand five-source drop fixture that creates a stunning focal point in any room.',
    price: 75000,
    originalPrice: 165000,
    images: ['/images/products/Pendant-&-Drop-Lighting/5-in-1-dropping-light-75000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 8,
    rating: 4.9,
    reviews: 5
  },
  {
    id: '12-bulb-nordic-light',
    name: '12 Bulb Nordic Light',
    description: 'Architectural Nordic design featuring 12 integrated bulbs for high-impact illumination.',
    price: 150000,
    originalPrice: 350000,
    images: ['/images/products/Pendant-&-Drop-Lighting/12-bulb-nordic-light-150000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 5,
    rating: 5.0,
    reviews: 3
  },
  {
    id: 'compact-nordic-crystal-drop',
    name: 'Compact Nordic Crystal Drop Light',
    description: 'Refined crystal drop lighting in a compact Nordic silhouette.',
    price: 140000,
    originalPrice: 285000,
    images: ['/images/products/Pendant-&-Drop-Lighting/compact-nordic-crystal-drop-light-140000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 6,
    rating: 4.9,
    reviews: 4
  },
  {
    id: 'led-drop-light-sold',
    name: 'LED Drop Light',
    description: 'Sleek and energy-efficient LED drop lighting solution.',
    price: 40000,
    originalPrice: 95000,
    images: ['/images/products/Pendant-&-Drop-Lighting/led-drop-light-40000-sold-out.avif'],
    category: 'Pendant & Drop Lighting',
    isSoldOut: true,
    rating: 4.7,
    reviews: 12
  },
  {
    id: 'luxury-nordic-rain-drop-chandelier-pdl',
    name: 'Luxury Nordic Rain Drop Chandelier',
    description: 'Breathtaking chandelier featuring cascading crystals inspired by Nordic rain.',
    price: 400000,
    originalPrice: 950000,
    images: ['/images/products/Pendant-&-Drop-Lighting/luxury-nordic-rain-drop-chandelier-400000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 3,
    rating: 5.0,
    reviews: 9
  },
  {
    id: 'luxury-unique-pendant-drop',
    name: 'Luxury Unique Pendant Drop Light',
    description: 'A one-of-a-kind pendant piece for the distinguished home.',
    price: 80000,
    originalPrice: 185000,
    images: ['/images/products/Pendant-&-Drop-Lighting/luxury-unique-pendant-drop-light-80000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 7,
    rating: 4.8,
    reviews: 6
  },
  {
    id: 'modern-quality-luxury-crystal-bracket-pdl',
    name: 'Modern Luxury Crystal Wall Bracket',
    description: 'Designer-grade wall bracket using high-quality crystals.',
    price: 10000,
    originalPrice: 28000,
    images: ['/images/products/Pendant-&-Drop-Lighting/modern-quality-luxury-crystal-led-wall-bracket-10000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 20,
    rating: 4.7,
    reviews: 15
  },
  {
    id: 'modern-design-nordic-wasoli',
    name: 'Modern Nordic Wasoli Drop Light',
    description: 'Clean lines and modern Nordic aesthetic in a Wasoli drop light.',
    price: 60000,
    originalPrice: 145000,
    images: ['/images/products/Pendant-&-Drop-Lighting/modern-design-nordic-wasoli-drop-light-60000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 10,
    rating: 4.8,
    reviews: 4
  },
  {
    id: 'modern-nordic-gold-chandelier',
    name: 'Modern Nordic Gold Chandelier',
    description: 'Striking gold-finished Nordic chandelier for elegant dining rooms.',
    price: 120000,
    originalPrice: 285000,
    images: ['/images/products/Pendant-&-Drop-Lighting/modern-nordic-gold-chandelier-120000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 4,
    rating: 4.9,
    reviews: 8
  },
  {
    id: 'modern-nordic-light-premium',
    name: 'Modern Nordic Light',
    description: 'High-end Nordic lighting fixture with architectural appeal.',
    price: 400000,
    originalPrice: 850000,
    images: ['/images/products/Pendant-&-Drop-Lighting/modern-nordic-light-400000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 3,
    rating: 5.0,
    reviews: 11
  },
  {
    id: 'modern-led-crystal-chandelier-drop-pdl',
    name: 'Modern LED Crystal Chandelier',
    description: 'A fusion of energy-efficient LEDs and premium decorative crystals.',
    price: 450000,
    originalPrice: 985000,
    images: ['/images/products/Pendant-&-Drop-Lighting/modern-led-crystal-chandelier-450000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 2,
    rating: 5.0,
    reviews: 7
  },
  {
    id: 'bird-chandelier-dining-kitchen',
    name: 'Bird Chandelier LED Light',
    description: 'Whimsical yet luxurious bird-inspired chandelier, perfect for dining and kitchen spaces.',
    price: 75000,
    originalPrice: 185000,
    images: ['/images/products/Pendant-&-Drop-Lighting/new-design-bird-chandelier-led-light-for-dinning-&-kitchen-75000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 6,
    rating: 4.9,
    reviews: 5
  },
  {
    id: 'new-design-crystal-drop-light',
    name: 'New Design Crystal Drop Light',
    description: 'The latest in crystal drop design, offering superior refraction and style.',
    price: 75000,
    originalPrice: 185000,
    images: ['/images/products/Pendant-&-Drop-Lighting/new-design-crystal-drop-light-75000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 9,
    rating: 4.8,
    reviews: 4
  },
  {
    id: 'new-unique-design-led-light',
    name: 'New Unique Design LED Light',
    description: 'Avant-garde LED lighting solution with a truly unique silhouette.',
    price: 120000,
    originalPrice: 285000,
    images: ['/images/products/Pendant-&-Drop-Lighting/new-unique-design-led-light-120000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 5,
    rating: 4.9,
    reviews: 3
  },
  {
    id: 'rafted-to-dazzle-chandelier',
    name: 'Modern Dazzle Chandelier Light',
    description: 'Meticulously crafted to dazzle, a perfect blend of modern design and light.',
    price: 190000,
    originalPrice: 485000,
    images: ['/images/products/Pendant-&-Drop-Lighting/rafted-to-dazzle-the-perfect-blend-of-modern-design-chandelier-light-190000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 4,
    rating: 5.0,
    reviews: 6
  },
  {
    id: 'stylish-led-drop-light',
    name: 'Stylish LED Drop Light',
    description: 'Fashionable LED drop light for contemporary interior themes.',
    price: 45000,
    originalPrice: 95000,
    images: ['/images/products/Pendant-&-Drop-Lighting/stylish-led-drop-light-45000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 14,
    rating: 4.7,
    reviews: 9
  },
  {
    id: 'unique-3way-round-led',
    name: 'Unique 3-Way Round LED Light',
    description: 'Triple round LED light source providing balanced, modern illumination.',
    price: 75000,
    originalPrice: 185000,
    images: ['/images/products/Pendant-&-Drop-Lighting/unique-3way-round-led-light-75000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 8,
    rating: 4.8,
    reviews: 5
  },
  {
    id: 'unique-4way-ball-led',
    name: 'Unique 4-Way Ball LED Drop Light',
    description: 'Architectural spherical LED drop light with four points of brilliance.',
    price: 80000,
    originalPrice: 195000,
    images: ['/images/products/Pendant-&-Drop-Lighting/unique-4-way-ball-led-drop-light-80000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 6,
    rating: 4.9,
    reviews: 7
  },
  {
    id: 'unique-butterfly-led-dropping',
    name: 'Unique Butterfly LED Dropping Light',
    description: 'Graceful butterfly-inspired LED drop light for a touch of artistic elegance.',
    price: 120000,
    originalPrice: 285000,
    images: ['/images/products/Pendant-&-Drop-Lighting/unique-butterfly-led-dropping-light-120000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 4,
    rating: 5.0,
    reviews: 8
  },
  {
    id: 'unique-design-2way-drop',
    name: 'Unique Design 2-Way Drop Light',
    description: 'Dual-source drop light featuring a modern, balanced design.',
    price: 35000,
    originalPrice: 85000,
    images: ['/images/products/Pendant-&-Drop-Lighting/unique-design-2-way-drop-light-35000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 11,
    rating: 4.7,
    reviews: 6
  },
  {
    id: 'unique-drop-light-standard',
    name: 'Unique Drop Light',
    description: 'A versatile and unique drop light for any modern residential space.',
    price: 7000,
    originalPrice: 18500,
    images: ['/images/products/Pendant-&-Drop-Lighting/unique-drop-light-70000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 10,
    rating: 4.8,
    reviews: 4
  },
  {
    id: 'unique-track-led-drop',
    name: 'Unique Track LED Drop Light',
    description: 'Track-mounted LED drop light for industrial-modern aesthetics.',
    price: 100000,
    originalPrice: 225000,
    images: ['/images/products/Pendant-&-Drop-Lighting/unique-track-led-drop-light-100000.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 7,
    rating: 4.9,
    reviews: 5
  },
  {
    id: 'unique-ring-drop-light',
    name: 'Unique Ring Drop Light',
    description: 'Sculptural circular ring drop pendant providing ambient downlighting for high-ceiling dining rooms.',
    price: 70000,
    originalPrice: 150000,
    images: ['/images/products/Pendant-&-Drop-Lighting/unique-ring-drop-light-70000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 12,
    rating: 4.8,
    reviews: 9
  },
  {
    id: 'modern-crown-led-pendant-drop',
    name: 'Modern Crown LED Pendant Drop',
    description: 'Regal crown silhouette pendant luminaire with refined LED accents for luxurious kitchen islands.',
    price: 40000,
    originalPrice: 95000,
    images: ['/images/products/Pendant-&-Drop-Lighting/modern-crown-led-pendant-drop-40000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 14,
    rating: 4.8,
    reviews: 11
  },
  {
    id: 'round-led-pendant-drop-light',
    name: 'Round LED Pendant Drop Light',
    description: 'Spherical LED pendant light delivering soft, uniform illumination with minimalist elegance.',
    price: 45000,
    originalPrice: 100000,
    images: ['/images/products/Pendant-&-Drop-Lighting/round-led-pendant-drop-light-45000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 10,
    rating: 4.7,
    reviews: 8
  },
  {
    id: 'modern-led-fan-light',
    name: 'Modern LED Fan Drop Light',
    description: 'Contemporary dual-purpose fan and LED drop light ensuring quiet airflow and brilliant downlighting.',
    price: 80000,
    originalPrice: 180000,
    images: ['/images/products/Pendant-&-Drop-Lighting/modern-led-fan-light-80000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 6,
    rating: 4.9,
    reviews: 14
  },
  {
    id: 'elegant-mosaic-pendant-light',
    name: 'Elegant Mosaic Pendant Light',
    description: 'Artisanal textured mosaic glass pendant throwing mesmerizing light reflections across counters and dining tables.',
    price: 35000,
    originalPrice: 80000,
    images: ['/images/products/Pendant-&-Drop-Lighting/elegant-mosaic-pendant-light-35000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 15,
    rating: 4.9,
    reviews: 12
  },
  {
    id: 'unique-pineapple-led-pendant-drop-light',
    name: 'Unique Pineapple LED Pendant Drop Light',
    description: 'Artistic textured pineapple silhouette pendant light crafted from faceted glass and polished metal.',
    price: 50000,
    originalPrice: 110000,
    images: ['/images/products/Pendant-&-Drop-Lighting/unique-pineapple-led-pendant-drop-light-50000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 8,
    rating: 4.8,
    reviews: 10
  },
  {
    id: 'modern-led-square-drop-pendant-light',
    name: 'Modern LED Square Drop Pendant Light',
    description: 'Geometric square tier drop pendant delivering crisp architectural symmetry and high-lumen output.',
    price: 100000,
    originalPrice: 220000,
    images: ['/images/products/Pendant-&-Drop-Lighting/modern-led-square-drop-pendant-light-100000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 7,
    rating: 5.0,
    reviews: 15
  },
  {
    id: 'unique-round-curved-led-drop-light',
    name: 'Unique Curved Round LED Drop Light',
    description: 'Organic fluid ribbon drop luminaire with seamless LED diffusion for grand modern spaces.',
    price: 120000,
    originalPrice: 260000,
    images: ['/images/products/Pendant-&-Drop-Lighting/unique-ound-led-drop-light-120000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 5,
    rating: 5.0,
    reviews: 16
  },
  {
    id: 'led-drop-pendant-light-65k',
    name: 'LED Drop Pendant Light 65K',
    description: 'Refined vertical drop pendant light with brushed metallic accents and warm diffused illumination.',
    price: 65000,
    originalPrice: 140000,
    images: ['/images/products/Pendant-&-Drop-Lighting/led-drop-pendant-light-65000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 12,
    rating: 4.8,
    reviews: 13
  },
  {
    id: 'led-drop-pendant-light-40k',
    name: 'LED Drop Pendant Light 40K',
    description: 'Sleek minimalist cylinder drop pendant light providing focused downward illumination.',
    price: 40000,
    originalPrice: 90000,
    images: ['/images/products/Pendant-&-Drop-Lighting/led-drop-pendant-light-40000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 16,
    rating: 4.7,
    reviews: 7
  },
  {
    id: 'led-pendant-drop-lights-ensemble',
    name: 'LED Pendant Drop Lights Ensemble',
    description: 'Coordinated multi-drop pendant cluster designed to enhance breakfast nooks and bar counters.',
    price: 40000,
    originalPrice: 95000,
    images: ['/images/products/Pendant-&-Drop-Lighting/led-pendant-drop-lights-40000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 14,
    rating: 4.8,
    reviews: 9
  },
  {
    id: 'led-pendant-drop-light-65k-sold-out',
    name: 'LED Pendant Drop Light (Sold Out)',
    description: 'A sought-after architectural drop pendant with premium metallic finish. Currently out of stock.',
    price: 65000,
    originalPrice: 145000,
    images: ['/images/products/Pendant-&-Drop-Lighting/led-pendant-drop-light-65000-sold-out_result.avif'],
    category: 'Pendant & Drop Lighting',
    isSoldOut: true,
    stock: 0,
    rating: 4.9,
    reviews: 18
  },
  {
    id: 'led-pendant-ball-drop-light',
    name: 'LED Pendant Ball Drop Light',
    description: 'Opal glass orb suspended from slender brass hardware casting a warm atmospheric glow.',
    price: 60000,
    originalPrice: 130000,
    images: ['/images/products/Pendant-&-Drop-Lighting/led-pendant-ball-drop-light-60000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 11,
    rating: 4.8,
    reviews: 10
  },
  {
    id: 'led-coiled-pendant-drop-light',
    name: 'LED Coiled Pendant Drop Light',
    description: 'Dynamic spiral-coiled LED silhouette that creates an engaging focal point from every angle.',
    price: 60000,
    originalPrice: 135000,
    images: ['/images/products/Pendant-&-Drop-Lighting/led-coiled-pendant-drop-light-60000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 9,
    rating: 4.9,
    reviews: 12
  },
  {
    id: 'led-pineapple-pendant-light-sold-out',
    name: 'LED Pineapple Pendant Light (Sold Out)',
    description: 'Faceted crystal pineapple motif drop pendant. Highly popular and currently sold out.',
    price: 65000,
    originalPrice: 145000,
    images: ['/images/products/Pendant-&-Drop-Lighting/led-pineapple-pendant-light-65000-sold-out_result.avif'],
    category: 'Pendant & Drop Lighting',
    isSoldOut: true,
    stock: 0,
    rating: 5.0,
    reviews: 21
  },
  {
    id: 'led-pendant-drop-light-30k',
    name: 'LED Pendant Drop Light 30K',
    description: 'Compact accent drop light delivering warm, focused illumination for modern interiors.',
    price: 30000,
    originalPrice: 70000,
    images: ['/images/products/Pendant-&-Drop-Lighting/led-pendant-drop-light-30000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 18,
    rating: 4.7,
    reviews: 8
  },
  {
    id: 'led-dining-ball-drop-light-sold-out',
    name: 'LED Dining Ball Drop Light (Sold Out)',
    description: 'Grand dining cluster with floating luminous globes. Currently sold out due to high demand.',
    price: 100000,
    originalPrice: 220000,
    images: ['/images/products/Pendant-&-Drop-Lighting/led-dining-ball-drop-light-100000-sold-out_result.avif'],
    category: 'Pendant & Drop Lighting',
    isSoldOut: true,
    stock: 0,
    rating: 5.0,
    reviews: 25
  },
  {
    id: 'modern-led-pendant-drop-light-50k',
    name: 'Modern LED Pendant Drop Light 50K',
    description: 'Streamlined architectural drop fixture providing generous downward illumination with clean lines.',
    price: 50000,
    originalPrice: 115000,
    images: ['/images/products/Pendant-&-Drop-Lighting/modern-led-pendant-drop-light-50000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 12,
    rating: 4.8,
    reviews: 11
  },
  {
    id: 'stylish-led-round-drop-light',
    name: 'Stylish LED Round Drop Light',
    description: 'Statement luxury round LED drop light with layered concentric illumination for high-ceiling rooms.',
    price: 120000,
    originalPrice: 270000,
    images: ['/images/products/Pendant-&-Drop-Lighting/stylish-led-round-led-drop-light-120000_result.avif'],
    category: 'Pendant & Drop Lighting',
    stock: 6,
    rating: 4.9,
    reviews: 15
  },

  // SIDE LAMPS & STANDING LAMPS COLLECTION
  {
    id: 'bed-side-lamp',
    name: 'Bed Side Lamp',
    description: 'A sophisticated bedside lighting solution designed to provide a soft, warm glow for peaceful evenings.',
    price: 50000,
    originalPrice: 125000,
    images: ['/images/products/Side-Lamps-&-Standing-Lamps/bed-side-lamp-50000.avif'],
    category: 'Side Lamps & Standing Lamps',
    material: 'Premium Ceramic & Fabric Shade',
    stock: 15,
    rating: 4.8,
    reviews: 9
  },
  {
    id: 'unique-standing-led-lamp',
    name: 'Unique Standing LED Lamp',
    description: 'An architectural floor lamp featuring advanced LED technology and a minimalist silhouette for modern living spaces.',
    price: 95000,
    originalPrice: 245000,
    images: ['/images/products/Side-Lamps-&-Standing-Lamps/unique-standing-led-lamp-95000.avif'],
    category: 'Side Lamps & Standing Lamps',
    material: 'Brushed Aluminum & Integrated LED',
    dimensions: '160cm Height',
    stock: 8,
    rating: 5.0,
    reviews: 14
  },

  // SWITCHES & SOCKETS COLLECTION
  {
    id: '1-gang-2-way-switch',
    name: '1 Gang 2 Way Switch',
    description: 'Premium quality single gang two-way switch, featuring a refined architectural finish and superior tactile feedback.',
    price: 2500,
    originalPrice: 8500,
    images: ['/images/products/Switches-&-Sockets/1-gang-2-way-switch-2500.avif'],
    category: 'Switches & Sockets',
    material: 'Durable Polycarbonate & Metal Accents',
    stock: 40,
    rating: 4.9,
    reviews: 12
  },
  {
    id: '2-gang-2-way-switch',
    name: '2 Gang 2 Way Switch',
    description: 'Architectural grade double gang switch designed for multi-point lighting control with a sleek modern aesthetic.',
    price: 3000,
    originalPrice: 10500,
    images: ['/images/products/Switches-&-Sockets/2-gang-2-way-switch-3000.avif'],
    category: 'Switches & Sockets',
    material: 'Premium Fire-retardant Polymer',
    stock: 35,
    rating: 4.8,
    reviews: 8
  },
  {
    id: '3-gang-2-way-switch',
    name: '3 Gang 2 Way Switch',
    description: 'Triple gang switch offering comprehensive lighting management from a single refined wall plate.',
    price: 5000,
    originalPrice: 15500,
    images: ['/images/products/Switches-&-Sockets/3-gang-2-way-switch-5000.avif'],
    category: 'Switches & Sockets',
    material: 'Brushed Finish Polycarbonate',
    stock: 25,
    rating: 5.0,
    reviews: 6
  },
  {
    id: '13a-multi-big-button-socket',
    name: '13A Multi Big Button Socket',
    description: 'High-capacity 13A socket featuring oversized controls for ease of use and a modern minimalist silhouette.',
    price: 3000,
    originalPrice: 12500,
    images: ['/images/products/Switches-&-Sockets/13a-multi-big-button-socket-3000.avif'],
    category: 'Switches & Sockets',
    material: 'Impact-resistant Housing',
    stock: 30,
    rating: 4.7,
    reviews: 15
  },
  {
    id: '20a-switch-water-heater',
    name: '20A Water Heater Switch',
    description: 'Robust 20A switch specifically engineered for high-load appliances like water heaters, ensuring safety and durability.',
    price: 3000,
    originalPrice: 12500,
    images: ['/images/products/Switches-&-Sockets/20a-switch-water-heater-3000.avif'],
    category: 'Switches & Sockets',
    material: 'High-thermal Stability Resin',
    stock: 20,
    rating: 4.9,
    reviews: 10
  },
  {
    id: 'double-13a-multi-big-button-socket',
    name: 'Double 13A Multi Big Button Socket',
    description: 'Dual capacity 13A power outlet featuring the signature big button design for architectural consistency.',
    price: 5000,
    originalPrice: 18500,
    images: ['/images/products/Switches-&-Sockets/double-13a-multi-big-button-socket-5000.avif'],
    category: 'Switches & Sockets',
    material: 'High-gloss Durable Polymer',
    stock: 15,
    rating: 5.0,
    reviews: 7
  },
  {
    id: 'double-socket',
    name: 'Premium Double Socket',
    description: 'Classic double power outlet designed to provide reliable connectivity with a refined, understated finish.',
    price: 5000,
    originalPrice: 18500,
    images: ['/images/products/Switches-&-Sockets/double-socket-5000.avif'],
    category: 'Switches & Sockets',
    stock: 25,
    rating: 4.8,
    reviews: 21
  },
  {
    id: 'single-socket',
    name: 'Premium Single Socket',
    description: 'Single power outlet that combines functional safety with a clean, modern design language.',
    price: 3000,
    originalPrice: 12500,
    images: ['/images/products/Switches-&-Sockets/single-socket-3000.avif'],
    category: 'Switches & Sockets',
    stock: 40,
    rating: 4.7,
    reviews: 18
  },
  {
    id: '13a-single-socket-with-usb-type-c',
    name: '13A Single Socket with USB Type-C',
    description: 'Modern 13A luxury wall socket equipped with fast-charging USB-A and Type-C ports in a pristine premium finish.',
    price: 8000,
    originalPrice: 18000,
    images: ['/images/products/Switches-&-Sockets/13A-single-socket-with-USB-Type-c-8000_result.avif'],
    category: 'Switches & Sockets',
    stock: 35,
    rating: 4.9,
    reviews: 20
  },
  {
    id: '13a-double-socket-with-usb-type-c',
    name: '13A Double Socket with USB Type-C',
    description: 'Twin 13A switched electrical socket featuring dual integrated USB and Type-C fast chargers with fire-resistant casing.',
    price: 13000,
    originalPrice: 28000,
    images: ['/images/products/Switches-&-Sockets/13A-double-socket-with-usb-type-c-13000_result.avif'],
    category: 'Switches & Sockets',
    stock: 25,
    rating: 5.0,
    reviews: 28
  },
  {
    id: '13amps-single-smart-wifi-socket-with-tuya',
    name: '13Amps Single Smart WiFi Socket with Tuya',
    description: 'Smart home automation 13A socket powered by Tuya IoT, enabling remote phone control, scheduling, and voice assistance.',
    price: 24000,
    originalPrice: 50000,
    images: ['/images/products/Switches-&-Sockets/13Amps-single-smart-wifi-socket-with-tuya-24000_result.avif'],
    category: 'Switches & Sockets',
    stock: 15,
    rating: 4.9,
    reviews: 14
  },
  {
    id: '13amps-double-smart-wifi-socket-with-usb',
    name: '13Amps Double Smart WiFi Socket with USB',
    description: 'Dual-gang smart WiFi wall outlet with USB charging, voice control integration, and app-based energy monitoring.',
    price: 44000,
    originalPrice: 95000,
    images: ['/images/products/Switches-&-Sockets/13amps-double-smart-wifi-socket-with-usb-44000_result.avif'],
    category: 'Switches & Sockets',
    stock: 10,
    rating: 5.0,
    reviews: 19
  },
  {
    id: 'wifi-smart-switch-1-gang',
    name: 'WiFi Smart Switch 1 Gang',
    description: 'Tempered glass touch panel 1-gang smart WiFi switch with backlight indicator and seamless smartphone app control.',
    price: 21000,
    originalPrice: 45000,
    images: ['/images/products/Switches-&-Sockets/wifi-smart-switch-1-gang-21000_result.avif'],
    category: 'Switches & Sockets',
    stock: 20,
    rating: 4.8,
    reviews: 12
  },

  // TURKEY COLLECTION
  {
    id: 'tufted-turkey-chairs-tc',
    name: 'Tufted Turkey Grand Chairs',
    description: 'Exquisite hand-tufted grand chairs from our royal Turkey collection, featuring luxury velvet upholstery and ornate gold leaf craftsmanship.',
    price: 8000000,
    originalPrice: 22000000,
    images: ['/images/products/Turkey-Collections/tufted-turkey-chairs-8000000.avif'],
    category: 'Turkey Collection',
    material: 'Velvet & Hand-carved Gilded Wood',
    stock: 1,
    rating: 5.0,
    reviews: 4
  },

  // WALL BRACKET LIGHTING COLLECTION
  {
    id: '2-in-1-led-wall-bracket',
    name: '2 in 1 LED Wall Bracket Light',
    description: 'Versatile dual-source LED wall bracket offering flexible illumination for modern bedrooms and corridors.',
    price: 22000,
    originalPrice: 48500,
    images: ['/images/products/Wall-Bracket-Lighting/2-in-1-led-wall-bracket-light-22000.avif'],
    category: 'Wall Bracket Lighting',
    material: 'Aluminum & Acrylic',
    stock: 15,
    rating: 4.8,
    reviews: 7
  },
  {
    id: 'decorative-led-wall-bracket-fitting',
    name: 'Decorative LED Wall Bracket',
    description: 'An artistic lighting fixture that adds a layer of sophisticated texture to your walls.',
    price: 20000,
    originalPrice: 45000,
    images: ['/images/products/Wall-Bracket-Lighting/decorative-led-wall-bracket-20000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 12,
    rating: 4.7,
    reviews: 5
  },
  {
    id: 'decorative-wall-bracket-light',
    name: 'Decorative Wall Bracket Light',
    description: 'Ornate wall-mounted lighting solution designed for high-end residential interiors.',
    price: 24000,
    originalPrice: 52000,
    images: ['/images/products/Wall-Bracket-Lighting/decorative-wall-bracket-light-24000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 10,
    rating: 4.9,
    reviews: 8
  },
  {
    id: 'deer-wall-bracket-light',
    name: 'Deer Wall Bracket Light',
    description: 'Nature-inspired wall lighting featuring a graceful deer silhouette in a gold finish.',
    price: 22000,
    originalPrice: 48500,
    images: ['/images/products/Wall-Bracket-Lighting/deer-wall-bracket-light-22000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 6,
    rating: 5.0,
    reviews: 11
  },
  {
    id: 'durable-and-stylish-wall-bracket',
    name: 'Durable and Stylish LED Wall Bracket',
    description: 'A robust yet fashion-forward lighting choice for modern living spaces.',
    price: 19000,
    originalPrice: 43500,
    images: ['/images/products/Wall-Bracket-Lighting/durable-and-stylish-led-wall-bracket-19000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 18,
    rating: 4.8,
    reviews: 4
  },
  {
    id: 'durable-led-wall-bracket-std',
    name: 'Durable LED Wall Bracket',
    description: 'Reliable architectural lighting with high-grade LED components.',
    price: 19000,
    originalPrice: 43500,
    images: ['/images/products/Wall-Bracket-Lighting/durable-led-wall-bracket-19000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 22,
    rating: 4.7,
    reviews: 6
  },
  {
    id: 'luxury-home-rooms-wall-bracket',
    name: 'Luxury Home Rooms Wall Bracket Light',
    description: 'Premium wall lighting designed specifically for distinguished master suites.',
    price: 25000,
    originalPrice: 55000,
    images: ['/images/products/Wall-Bracket-Lighting/luxury-home-rooms-wall-bracket-light-25000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 9,
    rating: 4.9,
    reviews: 13
  },
  {
    id: 'luxury-double-golden-bird',
    name: 'Luxury Double Golden Bird Wall Bracket',
    description: 'An exquisite piece of art featuring two golden birds illuminated by a soft LED glow.',
    price: 35000,
    originalPrice: 75000,
    images: ['/images/products/Wall-Bracket-Lighting/luxury-double-golden-bird-wall-bracket-light-35000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 5,
    rating: 5.0,
    reviews: 19
  },
  {
    id: 'luxury-quality-mounted-bird',
    name: 'Luxury Quality Mounted Wall Bird Light',
    description: 'Sophisticated wall-mounted bird sculpture light with architectural detailing.',
    price: 20000,
    originalPrice: 45000,
    images: ['/images/products/Wall-Bracket-Lighting/luxury-quality-mounted-wall-bird-light-20000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 11,
    rating: 4.8,
    reviews: 7
  },
  {
    id: 'modern-and-energy-efficient-bracket',
    name: 'Modern and Energy-Efficient LED Wall Bracket',
    description: 'High-output LED wall bracket that combines modern style with low energy consumption.',
    price: 22000,
    originalPrice: 48500,
    images: ['/images/products/Wall-Bracket-Lighting/modern-and-energy-efficient-led-wall-bracket-22000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 14,
    rating: 4.9,
    reviews: 10
  },
  {
    id: 'modern-design-wall-bracket-v2',
    name: 'Modern Design Wall Bracket',
    description: 'Clean lines and a minimalist aesthetic for contemporary interior themes.',
    price: 17000,
    originalPrice: 38500,
    images: ['/images/products/Wall-Bracket-Lighting/modern-design-wall-bracket-17000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 25,
    rating: 4.7,
    reviews: 5
  },
  {
    id: 'modern-horn-rooms-bracket',
    name: 'Modern Horn Rooms Bracket',
    description: 'A unique horn-inspired wall bracket that adds a bold architectural statement to any room.',
    price: 25000,
    originalPrice: 54000,
    images: ['/images/products/Wall-Bracket-Lighting/modern-horn-rooms-bracket-25000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 8,
    rating: 5.0,
    reviews: 6
  },
  {
    id: 'modern-led-wall-bracket-light',
    name: 'Modern LED Wall Bracket',
    description: 'Sleek LED fixture providing efficient and stylish wall illumination.',
    price: 17000,
    originalPrice: 38500,
    images: ['/images/products/Wall-Bracket-Lighting/modern-led-wall-bracket-17000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 30,
    rating: 4.8,
    reviews: 12
  },
  {
    id: 'modern-room-wall-bracket',
    name: 'Modern Room Wall Bracket Light',
    description: 'Versatile wall lighting solution for bedrooms, living areas, and hallways.',
    price: 15000,
    originalPrice: 32000,
    images: ['/images/products/Wall-Bracket-Lighting/modern-room-wall-bracket-light-15000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 20,
    rating: 4.6,
    reviews: 9
  },
  {
    id: 'modern-wall-bracket-with-bulb',
    name: 'Modern Wall Bracket with Bulb',
    description: 'A complete lighting solution featuring a modern bracket and high-performance bulb.',
    price: 17000,
    originalPrice: 38500,
    images: ['/images/products/Wall-Bracket-Lighting/modern-wall-bracket-with-bulb-17000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 16,
    rating: 4.7,
    reviews: 4
  },
  {
    id: 'nodic-creative-feather-bracket',
    name: 'Nordic Modern Creative Feather Wall Bracket',
    description: 'Delicate feather-inspired design that adds a soft, creative touch to your walls.',
    price: 15000,
    originalPrice: 35000,
    images: ['/images/products/Wall-Bracket-Lighting/nodic-modern-creative-feather-wall-bracket-15000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 12,
    rating: 4.9,
    reviews: 15
  },
  {
    id: 'nodic-creative-feather-light',
    name: 'Nordic Modern Creative Feather Wall Light',
    description: 'Larger format creative feather light for high-impact wall decor.',
    price: 20000,
    originalPrice: 46000,
    images: ['/images/products/Wall-Bracket-Lighting/nodic-modern-creative-feather-wall-ligh-20000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 10,
    rating: 5.0,
    reviews: 8
  },
  {
    id: 'unique-wall-bracket-std',
    name: 'Unique Wall Bracket',
    description: 'A one-of-a-kind wall bracket that serves as a permanent architectural addition to your home.',
    price: 19000,
    originalPrice: 44500,
    images: ['/images/products/Wall-Bracket-Lighting/unique-wall-bracket-19000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 15,
    rating: 4.8,
    reviews: 7
  },
  {
    id: 'unique-wall-led-light-fitting',
    name: 'Unique Wall LED Light',
    description: 'Avant-garde wall-mounted LED lighting with a distinctive silhouette.',
    price: 19000,
    originalPrice: 44500,
    images: ['/images/products/Wall-Bracket-Lighting/unique-wall-led-light-19000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 13,
    rating: 4.9,
    reviews: 5
  },
  {
    id: 'wall-bracket-light-basic',
    name: 'Wall Bracket Light',
    description: 'Essential wall lighting providing reliable performance and a clean look.',
    price: 8000,
    originalPrice: 22000,
    images: ['/images/products/Wall-Bracket-Lighting/wall-bracket-light-8000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 40,
    rating: 4.5,
    reviews: 21
  },
  {
    id: 'wall-bracket-light-premium',
    name: 'Wall Bracket Light Premium',
    description: 'High-quality wall bracket light for sophisticated residential lighting schemes.',
    price: 19000,
    originalPrice: 45000,
    images: ['/images/products/Wall-Bracket-Lighting/wall-bracket-light-19000.avif'],
    category: 'Wall Bracket Lighting',
    stock: 18,
    rating: 4.7,
    reviews: 14
  }
];
